- .travis.yml
> Extend Travis configuration to test different feature combinations

- .travis.yml
- CHANGELOG.md
- src/lib.rs
- src/rust.rs
> Implement de/serialization using the Display and FromStr traits

- src/rust.rs
- tests/rust.rs
Alter behaviour of empty string to allow for empty collections.
bors r+
> Add string collection tests

- CHANGELOG.md
- Cargo.toml
- README.md
- README.tpl
- src/lib.rs
> Add documentation + Version Bump

- .travis.yml
Let's see if this works
bors r+
> Clean Travis cache during cron builds

- CHANGELOG.md
- Cargo.toml
- README.md
- src/lib.rs
- src/rust.rs
Bump version to release the with_prefix! changes.
bors r+
> Small updates to the documentation

- rustfmt.toml
- src/json.rs
- src/lib.rs
- src/rust.rs
- src/with_prefix.rs
> Format with newer rustfmt

- CHANGELOG.md
- Cargo.toml
> Bump version to 0.2.2

- src/duplicate_key_impls/error_on_duplicate.rs
- src/duplicate_key_impls/first_value_wins.rs
- src/json.rs
- src/lib.rs
- src/rust.rs
* Re-Add deny missing docs, and fix errors
* Run Clippy and implement suggestions
bors r+
> Various Clippy and doc improvements

- CHANGELOG.md
- Cargo.toml
> Bump version to 0.2.3

- CHANGELOG.md
- Cargo.toml
> Bump version to 0.2.4

- .travis.yml
> Change kcov to tarpaulin

- CHANGELOG.md
- Cargo.toml
- src/rust.rs
> Helper which deserializes an empty string as `None`

- Cargo.toml
- src/rust.rs
- tests/rust.rs
This addresses the first two wishes from #32.
@upsuper: Ping, since you originally proposed this for addition to serde.
It would be nice to know if it works for you, since I generalized your implementation.
> Add documentation for HashMap and BTreeMap as tuple lists

- Cargo.toml
- src/chrono.rs
- src/json.rs
- src/lib.rs
- src/rust.rs
- src/with_prefix.rs
- tests/chrono.rs
- tests/rust.rs
- tests/version_numbers.rs
- tests/with_prefix.rs
Update all macro imports to use the new path style.
bors r+
> Bump minimal Rust version to 1.30.0

- CHANGELOG.md
- src/lib.rs
- src/rust.rs
- tests/rust.rs
> Add documentation for Tuple list to map helper

- .pre-commit-config.yaml
- Cargo.toml
This hook check line endings and prevents me from commiting to the master branch.
> Add pre-commit hook

- Cargo.toml
- README.md
- serde_with_macros/Cargo.toml
- serde_with_macros/src/lib.rs
- src/lib.rs
* Improve documentation on how to use the proc_macro attributes
* Correct use of the licence expressions
> Improve the documentaion

- serde_with_macros/Cargo.toml
- serde_with_macros/src/lib.rs
The proc-macro crates proc-macro2, quote, and syn got updated to version 1+.
> Update proc-macro dependencies to 1.0.0

- .github/workflows/publish-crates-io.yaml
> Fix typo in if condition of workflow

- src/de/impls.rs
- src/lib.rs
- src/ser/impls.rs
- src/utils.rs
- tests/serde_as.rs
> Convert Duration to f64

- .github/workflows/ci.yaml
- serde_with_macros/tests/compiler-messages.rs
* Ensure all checks are run against all crates in the workspace
* Run checks against pull requests and restrict it to pushes for bors
branches
* Disable incremental compilation
> Improve CI Workflow

- .github/workflows/ci.yaml
This hopefully works with PRs from forks now
> Use a newer version of the codecov action

- Cargo.toml
- src/with_prefix.rs
- tests/with_prefix.rs
> Serialize Unit variant to/form string

- Cargo.toml
- serde_with_macros/Cargo.toml
- serde_with_macros/src/lib.rs
- serde_with_macros/tests/compile-fail/serde_as.rs
- serde_with_macros/tests/compile-fail/serde_as.stderr
- tests/chrono.rs
- tests/hex.rs
- tests/json.rs
- tests/serde_as.rs
- tests/serde_as_macro.rs
> Add `serde_as` macro to make the new system more convenient to use

- src/formats.rs
- src/hex.rs
- tests/hex.rs
* Implement lower- and uppercase serialization
* Properly document module
* Add example doctest
> Improve hex module

- CHANGELOG.md
- Cargo.toml
- serde_with_macros/src/lib.rs
- src/json.rs
- src/lib.rs
- src/rust.rs
> Add more docs mainly for `serde_as` types

- .vscode/settings.json
- serde_with_macros/src/lib.rs
- src/chrono.rs
- src/de/impls.rs
- src/lib.rs
Also enable warnings and deny missing docs (again).
> Fix small documentation error, run some spell check

- CHANGELOG.md
- Cargo.toml
- README.md
- serde_with_macros/CHANGELOG.md
- serde_with_macros/Cargo.toml
- serde_with_macros/src/lib.rs
- src/lib.rs
- tests/version_numbers.rs
Bump serde_with_macros to 1.2.0-alpha.3
Bump serde_with to 1.5.0-alpha.2
> Bump Version for main and macro crate

- src/de/impls.rs
- src/ser/impls.rs
- tests/serde_as.rs
> Remove the special casing of 0-sized array implementations

- tests/utils.rs
assert_eq first takes the expected value and second the actual.
> Test utils: Correctly order expected and actual values

- Cargo.toml
- serde_with_macros/Cargo.toml
* Remove badges as they are no longer properly supported by crates.io
* Provide a better `include` list to remove unneeded files.
This also requires to specify a path for each test.
* Use a better `author` name
> Cleanup the Cargo.toml files

- CHANGELOG.md
- Cargo.toml
- README.md
- serde_with_macros/CHANGELOG.md
- serde_with_macros/Cargo.toml
- serde_with_macros/src/lib.rs
- src/lib.rs
> Bump serde_with to v1.5.0 and serde_with_macros to v1.2.0

- serde_with_macros/CHANGELOG.md
- serde_with_macros/Cargo.toml
- serde_with_macros/src/lib.rs
Update changelog to include fix from @adwhit in #186
> Bump serde_with_marcros to v1.2.1

- CHANGELOG.md
> Fix missing entry for latest version in changelog

- .github/workflows/audit.yaml
> Fix typo in audit.yaml

- src/guide/serde_as.md
> Document that deserializing optional field breaks with serde_as annotation

- CHANGELOG.md
- src/de/impls.rs
- src/guide/serde_as.md
- src/lib.rs
- src/rust.rs
- src/ser/impls.rs
- tests/serde_as.rs
Add the `serde_as` equivalent for `default_on_null`. It works similar to
`DefaultOnError`, but instead of all deserialization errors only on
null.
> Add DefaultOnNull

- src/lib.rs
- src/rust.rs
> Improve docs for DefaultOnError and default_on_error

- serde_with_macros/src/lib.rs
> Document the new `crate` argument on the derive macros.

- .github/workflows/publish-crates-io.yaml
Add an action which creates a Release with the content of the changelog.
> Add Changelog action to CI release

- CHANGELOG.md
- Cargo.toml
- src/de/impls.rs
- src/lib.rs
- src/ser/impls.rs
- src/utils/duration.rs
- tests/serde_as_duration.rs
> #194 Create more Duration/Timestamp adapters with different time units

- src/de/impls.rs
- src/rust.rs
- tests/json.rs
- tests/serde_as.rs
> Remove redundant semicolons

- src/lib.rs
- src/rust.rs
Fixes https://github.com/jonasbb/serde_with/issues/250
> add deserialize_ignore_any

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- src/rust.rs
* Mention it in the Changelog
* Add test cases
* Describe the secondary use case.
> Improve `deserialize_ignore_any`

- src/guide/serde_as.md
> Add missing brackets to serde_as guide for Vec -> Map convertion

- src/rust.rs
> Fix doc on `tuple_list_as_map`

- serde_with_macros/tests/version_numbers.rs
- tests/version_numbers.rs
> Fix compilation with newer nightly rust

- src/chrono.rs
- src/utils/duration.rs
> Fix clippy lint from_str_radix_10

- CHANGELOG.md
- serde_with_macros/CHANGELOG.md
> Add release dates to changelogs

- src/rust.rs
Make better use of the `utils::SeqIter` type.
bors r+
> Slight cleanup for the rust.rs file

- src/rust.rs
> Use MapIter from utils

- src/ser/impls.rs
> Relax some trait bounds for `SerializeAs` implementations

- src/de/const_arrays.rs
- src/formats.rs
> Fix some rustdoc warning

- src/de/impls.rs
- src/ser/impls.rs
- tests/serde_as/lib.rs
> Add support for more wrapper types

- CHANGELOG.md
- Cargo.toml
- README.md
- serde_with_macros/src/lib.rs
- src/lib.rs
> Bump Version to 1.8.0

- src/guide/serde_as.md
> Add example of implementing DeserializeAs for remote types.

- CHANGELOG.md
- Cargo.toml
- README.md
- serde_with_macros/src/lib.rs
- src/lib.rs
> Bump version to release Hex change

- .github/workflows/ci.yaml
> Use rust-cache to speedup CI runs

- CHANGELOG.md
- Cargo.toml
- README.md
- serde_with_macros/src/lib.rs
- src/lib.rs
> Bump version to release `FromInto` and `serde_conv!`

- CHANGELOG.md
- Cargo.toml
- README.md
- serde_with_macros/src/lib.rs
- src/lib.rs
> Bump version for bugfix release

- serde_with_macros/src/lib.rs
- serde_with_macros/src/utils.rs
- tests/version_numbers.rs
Some now clippy warnings about needless_borrow are fixed here.
bors r+
> Fix new clippy warnings

- CHANGELOG.md
- Cargo.toml
- README.md
- serde_with_macros/CHANGELOG.md
- serde_with_macros/Cargo.toml
- serde_with_macros/src/lib.rs
- src/lib.rs
serde_with -> 1.9.2
serde_with_macros -> 1.4.2
bors r+
> Bump Versions

- CHANGELOG.md
- Cargo.toml
- README.md
- serde_with_macros/src/lib.rs
- src/lib.rs
> Bump version to 1.9.3

- CHANGELOG.md
- Cargo.toml
- README.md
- serde_with_macros/src/lib.rs
- src/lib.rs
- src/with_prefix.rs
Closes #327 
I'm not sure how to document this and what is the preferred way to add the tests, so I decided to open a PR directly
> with_prefix macro - Visibility qualifier for generated module

- serde_with_macros/src/lib.rs
- serde_with_macros/tests/version_numbers.rs
- tests/version_numbers.rs
https://github.com/rust-lang/rust-clippy/issues/7422
> Suppress false positive in current clippy nightly

- serde_with_macros/tests/compile-fail/skip-none-not-struct.stderr
- serde_with_macros/tests/compiler-messages.rs
> Fix trybuild tests for updated error messages of Rust 1.54

- README.md
- src/lib.rs
> Slightly improve README/main docs

- serde_with_macros/src/lib.rs
- src/rust.rs
- src/ser/mod.rs
collect_str in particular is nicer than converting to a String first.
bors r+
> Use collect_str and collect_seq where applicable

- .vscode/settings.json
- CHANGELOG.md
- serde_with_macros/CHANGELOG.md
- serde_with_macros/src/lib.rs
- src/guide.md
- src/lib.rs
- src/rust.rs
- src/serde_conv.rs
> Fix some typos in various places

- CHANGELOG.md
- serde_with_macros/CHANGELOG.md
serde_with 1.10.0
serde_with_macros 1.5.0
bors merge
> Release-version

- tests/rust.rs
> Fix clippy::bool_assert_comparison warnings

- serde_with/src/guide/serde_as_transformations.md
- serde_with/src/hex.rs
> Improve documentation of the hex module

- .github/workflows/scorecards-analysis.yml
https://github.blog/2022-01-19-reducing-security-risk-oss-actions-opensff-scorecards-v4/
> Add the OpenSSF Scorecard as a weekly check

- serde_with/CHANGELOG.md
> Add `VecSkipError` to the changelog

- .github/workflows/audit.yaml
- .github/workflows/ci.yaml
- .github/workflows/publish-crates-io.yaml
> Ci-token-permission

- serde_with/src/de/const_arrays.rs
> Fix clippy warning

- .github/rust.json
- .github/workflows/ci.yaml
> Add problem matcher

- README.md
- serde_with/CHANGELOG.md
- serde_with/Cargo.toml
- serde_with/src/lib.rs
- serde_with_macros/CHANGELOG.md
- serde_with_macros/Cargo.toml
- serde_with_macros/src/lib.rs
> Bump versions to release macro fixes / improvements

- serde_with/CHANGELOG.md
> Use correct headers for changelog

- .devcontainer/Dockerfile
- serde_with/Cargo.toml
- serde_with/src/guide/serde_as_transformations.md
- serde_with_macros/tests/version_numbers.rs
* properly setup pre-commit in devcontainers
* Improve documentation
* Check version numbers in more places
bors merge
> A couple of small fixes

- serde_with/Cargo.toml
- serde_with/src/base64.rs
- serde_with/src/chrono.rs
- serde_with/src/guide.md
- serde_with/src/hex.rs
- serde_with/src/json.rs
- serde_with/src/lib.rs
- serde_with/src/rust.rs
- serde_with/src/serde_conv.rs
- serde_with/src/with_prefix.rs
- serde_with/tests/with_prefix.rs
> Replace `serde_derive` imports in test with imports from `serde`

- README.md
- serde_with/CHANGELOG.md
- serde_with/Cargo.toml
- serde_with/src/lib.rs
- serde_with_macros/Cargo.toml
- serde_with_macros/src/lib.rs
* Update changelog
* Include tests when publishing
bors merge
> Bump serde_with to v1.13.0

- serde_with/src/with_prefix.rs
- serde_with_test/tests/with_prefix.rs
> Ensure the `with_prefix!` macro uses properly namespaced items

- serde_with/src/de/mod.rs
- serde_with/src/ser/const_arrays.rs
- serde_with/tests/serde_as/enum_map.rs
> Fix nightly clippy warnings

- CONTRIBUTING.md
> Document how to add new crates

- serde_with/src/lib.rs
> Fix new nighly lint unused_macro_rules

- serde_with/src/lib.rs
- serde_with/tests/base64.rs
- serde_with/tests/chrono.rs
- serde_with/tests/derives/lib.rs
- serde_with/tests/hex.rs
- serde_with/tests/indexmap.rs
- serde_with/tests/json.rs
- serde_with/tests/rust.rs
- serde_with/tests/serde_as/lib.rs
- serde_with/tests/time_0_3.rs
- serde_with/tests/with_prefix.rs
https://github.com/rust-lang/rust-clippy/issues/8867
bors merge
> Fix clippy false positive

- README.md
- serde_with/CHANGELOG.md
- serde_with/Cargo.toml
- serde_with/src/lib.rs
- serde_with/tests/version_numbers.rs
- serde_with_macros/CHANGELOG.md
- serde_with_macros/Cargo.toml
- serde_with_macros/src/lib.rs
- serde_with_macros/tests/version_numbers.rs
> Bump versions to v2.0.0-rc.0

- serde_with/src/lib.rs
https://github.com/rust-lang/rust-clippy/issues/9101
bors r+
> Suppress issue with `clippy::explicit_auto_deref`

- README.md
- serde_with/src/lib.rs
- serde_with/src/with_prefix.rs
- serde_with_macros/src/lib.rs
> Cleanup links and attributes

- README.md
- serde_with/CHANGELOG.md
- serde_with/Cargo.toml
- serde_with/src/lib.rs
- serde_with_macros/CHANGELOG.md
- serde_with_macros/Cargo.toml
- serde_with_macros/src/lib.rs
> Bump versions to release v2.0.0

- .devcontainer/devcontainer.json
> Install newer git and fish in devcontainer

- serde_with_test/tests/flattened_maybe.rs
> Fix `clippy::assertions_on_result_states` in test code

- serde_with/src/enum_map.rs
- serde_with/src/hex.rs
- serde_with/src/lib.rs
> Fix a handful of doc links

- serde_with/src/chrono_0_4.rs
- serde_with/tests/chrono_0_4.rs
Switch from from_timestamp to from_timestamp_opt.
> Fix chrono deprecation warnings

- serde_with/CHANGELOG.md
- serde_with_macros/CHANGELOG.md
- serde_with_test/tests/derive_display_fromstr.rs
> Add test and changelog covering #526

- README.md
- serde_with/CHANGELOG.md
- serde_with/Cargo.toml
- serde_with/src/lib.rs
- serde_with_macros/CHANGELOG.md
- serde_with_macros/Cargo.toml
- serde_with_macros/src/lib.rs
> Bump version to v2.1.0

- serde_with/src/content/ser.rs
> Fix unnecessary ref and & in patterns

- serde_with/src/base64.rs
- serde_with/src/chrono_0_4.rs
- serde_with/src/de/impls.rs
- serde_with/src/hex.rs
- serde_with/src/time_0_3.rs
- serde_with/src/utils/duration.rs
- serde_with/tests/serde_as/enum_map.rs
- serde_with/tests/version_numbers.rs
> Fix clippy lint about format args

- serde_with/src/enum_map.rs
> Add a comment to enum_map

- serde_with/src/de/impls.rs
> Cleanup some of the deserialization code

- serde_with/CHANGELOG.md
- serde_with/src/content/de.rs
- serde_with/src/content/mod.rs
- serde_with/src/content/ser.rs
- serde_with/src/guide/serde_as_transformations.md
- serde_with/src/key_value_map.rs
- serde_with/src/lib.rs
- serde_with/src/utils.rs
- serde_with/tests/serde_as/key_value_map.rs
- serde_with/tests/serde_as/lib.rs
> Serialize a struct as a map entry with a field becoming the map key

- Cargo.lock
- README.md
- serde_with/CHANGELOG.md
- serde_with/Cargo.toml
- serde_with/src/lib.rs
- serde_with_macros/CHANGELOG.md
- serde_with_macros/Cargo.toml
- serde_with_macros/src/lib.rs
> Bump version to 2.3.0

- .github/workflows/publish-crates-io.yaml
> Remove deprecated set-output command from CI script

- serde_with/tests/serde_as/map_tuple_list.rs
https://github.com/jonasbb/serde_with/pull/572
https://github.com/jonasbb/serde_with/issues/565#issuecomment-1464583848
bors r+
> Add regression test for problems with #565/#566

- Cargo.lock
- serde_with_macros/Cargo.toml
- serde_with_macros/tests/compile-fail/serde_as.stderr
- serde_with_macros/tests/compile-fail/skip-none-always.stderr
- serde_with_macros/tests/compile-fail/skip-none-not-struct.stderr
> Force update the trybuild test fixtures

- serde_with/src/key_value_map.rs
- serde_with/src/lib.rs
- serde_with/src/utils.rs
> Fix clippy and nightly rust warnings

- .github/workflows/ci.yaml
> Switch the weekly CI run to Saturday as it is more conevenient for me

- serde_with/tests/serde_as/lib.rs
> Fix test to work with updated dependencies

- Cargo.lock
https://github.com/rust-lang/rust/issues/113152
https://github.com/dtolnay/proc-macro2/pull/391
bors r+
> Bump proc-macro2 to unbreak nightly

- serde_with/Cargo.toml
> Add no-std::no-alloc category to serde_with

- serde_with/src/key_value_map.rs
> Cleanup error messages that should not contain the string TODO

- Cargo.lock
- README.md
- serde_with/CHANGELOG.md
- serde_with/Cargo.toml
- serde_with/src/lib.rs
- serde_with_macros/CHANGELOG.md
- serde_with_macros/Cargo.toml
- serde_with_macros/src/lib.rs
> Bump version to v3.1.0

- .devcontainer/devcontainer.json
> Require 4-core CPUs from devcontainers

- CONTRIBUTING.md
- Cargo.lock
- Cargo.toml
- README.md
- serde_with/CHANGELOG.md
- serde_with/Cargo.toml
- serde_with/src/lib.rs
- serde_with_macros/CHANGELOG.md
- serde_with_macros/Cargo.toml
- serde_with_macros/src/lib.rs
> Bump version to v3.2.0

- .github/workflows/ci.yaml
* Use the newer feature names instead of the older unversioned ones
* Include indexmap_2
> Update no_std+alloc+optional test

- Cargo.lock
- Cargo.toml
- README.md
- serde_with/CHANGELOG.md
- serde_with/Cargo.toml
- serde_with/src/lib.rs
- serde_with_macros/CHANGELOG.md
- serde_with_macros/src/lib.rs
> Bump version to v3.3.0 for `hashbrown` support

- Cargo.lock
- Cargo.toml
- README.md
- serde_with/CHANGELOG.md
- serde_with/Cargo.toml
- serde_with/src/lib.rs
- serde_with/tests/serde_as/lib.rs
- serde_with_macros/CHANGELOG.md
- serde_with_macros/src/lib.rs
> Bump version to 3.4.0

- .github/workflows/publish-crates-io.yaml
- Cargo.toml
- serde_with/Cargo.toml
- serde_with/src/base64.rs
- serde_with/src/de/impls.rs
- serde_with/src/guide.md
- serde_with/src/rust.rs
- serde_with/tests/hashbrown_0_14.rs
- serde_with/tests/indexmap_1.rs
- serde_with/tests/indexmap_2.rs
- serde_with/tests/serde_as/collections.rs
- serde_with/tests/serde_as/lib.rs
- serde_with/tests/version_numbers.rs
- serde_with/tests/with_prefix.rs
- serde_with_macros/Cargo.toml
- serde_with_macros/src/apply.rs
- serde_with_macros/src/lib.rs
- serde_with_macros/tests/serde_as_issue_538.rs
Co-authored-by: Yuri Astrakhan <YuriAstrakhan@gmail.com>
> Simpler alternative to #669

- Cargo.lock
- Cargo.toml
- README.md
- serde_with/CHANGELOG.md
- serde_with/Cargo.toml
- serde_with/src/lib.rs
- serde_with_macros/CHANGELOG.md
- serde_with_macros/src/lib.rs
Release for all the `schemars` support implemented by @swlynch99
> Bump to v3.5.0

- serde_with/src/content/ser.rs
- serde_with/src/enum_map.rs
- serde_with/src/key_value_map.rs
- serde_with/src/lib.rs
- serde_with/tests/serde_as/map_tuple_list.rs
- serde_with_macros/src/lib.rs
https://github.com/rust-lang/rust/issues/121621
https://github.com/rust-lang/rust/issues/120363
> Silence problematic non_local_definitions behavior around references

- Cargo.lock
Update version-sync and schemars to get rid of any remaining syn v1 dependencies.
> Update dev dependencies

- .github/workflows/ci.yaml
- Cargo.lock
- Cargo.toml
- serde_with/CHANGELOG.md
- serde_with/Cargo.toml
- serde_with/tests/time_0_3.rs
> Bump time to 0.3.36 for nightly compatability

- serde_with/CHANGELOG.md
- serde_with/src/schemars_0_8.rs
> Make code compile with `schemars_0_8/preserve_order` enabled

- serde_with/src/lib.rs
- serde_with/src/rust.rs
- serde_with/src/serde_conv.rs
- serde_with_macros/src/lib.rs
Fix `manual_ok_err` and some Markdown formatting.
> Fix clippy links

- Cargo.lock
- serde_with/Cargo.toml
- serde_with/src/lib.rs
This gets rid of the doc_comment dependency.
> Copy a new version of the generate_guide! macro

- .cargo/audit.toml
> Ignore RUSTSEC-2024-0436

- serde_with/src/formats.rs
- serde_with/src/guide.md
- serde_with/src/guide/serde_as_transformations.md
- serde_with/src/lib.rs
- serde_with/src/schemars_0_9.rs
docs.rs shows some warnings about links in the doc comments.
https://docs.rs/crate/serde_with/3.12.0/builds/2224111
> Fix doc links

- Cargo.lock
- serde_with/Cargo.toml
* Update the document-features dependency to version 0.2.11.
* Add links to the external dependencies.
> Update the feature documentation

- serde_with/tests/schemars_0_8/main.rs
- serde_with/tests/schemars_0_9/main.rs
- serde_with/tests/schemars_1/main.rs
It merged imports differently than before
> Update formatting for nightly rust
