CHANGELOG.md, src/rust.rs
It allows to differentiate between missing values, null values, and
existing values, for example in JSON.
=> Add the double option helper

CHANGELOG.md, Cargo.toml, src/rust.rs
Some serialization formats might add the Some() while serializing
values, for example RON. This can be undesired if you want to provide an
optional value which is skipped if not set.
Resolves #7
Co-authored-by: Tim Ryan <id@timryan.org>
=> Adds option deserialization only inner value if Some(T)

.travis.yml, Cargo.toml
Take inspiration by the petgraph-graphml Travis configuration.
* Add Clippy tests for stable, beta, and nightly.
* Add a minimal versions test.
=> Update Travis CI configuration

Cargo.toml
This reduces the size of the crate file on crates.io
=> Exclude various config files from crates.io publishing

.travis.yml
This happens either on old toolchains or sometimes on nightly.
bors try
=> FIX: Ignore clippy if it is not available

src/rust.rs
This helper uses `FromIterator`/`IntoIterator` traits for collection
itself and `Display`/`FromStr` for each element.
=> Added `rust::seq_display_fromstr` to help de/serialize collections

.travis.yml
tarpaulin 0.6.11 removed a CLI option and made it fail
https://github.com/xd009642/tarpaulin/pull/187
=> Fix Travis build after tarpaulin update

.travis.yml, Cargo.toml, README.md, src/lib.rs, tests/version_numbers.rs
* Add codecov to crates.io badges
* Ensure the version numbers in the documentation stay in sync with the crate.
=> Maintenance Changes

.travis.yml, Cargo.toml
Large parts of the ecosystem do not support it.
=> Disable minimal-versions checking

.travis.yml, CHANGELOG.md, Cargo.toml, serde_with_macros/Cargo.toml, serde_with_macros/LICENSE-APACHE, serde_with_macros/LICENSE-MIT, serde_with_macros/README.md, serde_with_macros/src/lib.rs, serde_with_macros/tests/skip_serializing_null.rs, serde_with_macros/tests/version_numbers.rs, src/lib.rs
The `skip_serializing_null` attribute can be added to any struct and adds `#[serde(skip_serializing_if = "Option::is_none")]` to every `Option` field.
The intended use is for parsing data, e.g., from APIs, which has many optional values.
It turns
```rust
#[skip_serializing_null]
#[derive(Serialize)]
struct Data {
a: Option<String>,
b: Option<String>,
c: Option<String>,
d: Option<String>,
}
```
into
```rust
#[derive(Serialize)]
struct Data {
#[serde(skip_serializing_if = "Option::is_none")]
a: Option<String>,
#[serde(skip_serializing_if = "Option::is_none")]
b: Option<String>,
#[serde(skip_serializing_if = "Option::is_none")]
c: Option<String>,
#[serde(skip_serializing_if = "Option::is_none")]
d: Option<String>,
}
```
The issue was originally suggested at …
=> Add a `skip_serializing_null` attribute

serde_with_macros/CHANGELOG.md, serde_with_macros/Cargo.toml, serde_with_macros/src/lib.rs
`syn` was missing some feature dependencies, which where hidden due to the dev-dependency features leaking into the normal build.
This caused problems on doc.rs though.
=> Bump serde_with_macros version

src/with_prefix.rs
This documents the limitation regarding with_prefix and
deny_unknown_fields as raised in issue #57.
Closes #57
=> Improve the documentation for with_prefix

.travis.yml, CHANGELOG.md, serde_with_macros/CHANGELOG.md
* Run cargo audit
* Use tarpaulin also on stable Rust versions
* Bump minimal version to 1.31.1 to use Edition 2018
=> Improve CI pipeline

.travis.yml, serde_with_macros/Cargo.toml, serde_with_macros/tests/compile-fail/skip-none-always.rs, serde_with_macros/tests/compile-fail/skip-none-always.stderr, serde_with_macros/tests/compile-fail/skip-none-not-struct.rs, serde_with_macros/tests/compile-fail/skip-none-not-struct.stderr, serde_with_macros/tests/compiler-messages.rs
Use trybuild as an improvement over compiletest as the test framework
for the UI tests.
Older Rust versions (<1.35.0) have different error messages, so the new
UI tests fail on them, therefore gate them on the Rust version.
Closes #50
=> Add trybuild tests to check the error messages created by the macros

CHANGELOG.md, src/flatten_maybe.rs, src/lib.rs, src/rust.rs, tests/chrono.rs
This was wished in #35.
It apparently can be helpful for interacting with languages which have
other definitions of strings.
Closes #35
=> Add a deserialization adapter, which creates a Vec<u8> from string or bytes

.travis.yml, CHANGELOG.md
* smallvec is required for version-sync test
=> Bump min Rust to 1.36 because of Travis test failure

serde_with_macros/Cargo.toml
get_ident was only added in 1.0.3
=> Fix the minimal syn version for serde_with_macros

CHANGELOG.md, Cargo.toml, README.md, serde_with_macros/Cargo.toml, src/lib.rs
* Switch the badges to Github Actions instead of Travis.
* Remove link for proc-macro documentation, since doc reexport works now.
* Add version number to changelog title.
* Ignore the .github folder for crates archive.
=> Cleanup some oversights left in the last release

src/de/impls.rs, src/de/mod.rs, src/ser/impls.rs, src/utils.rs, tests/serde_as.rs
Sequence-ish types are types implementing IntoIterator and FromIterator. This includes BinaryHeap or HashSet.
=> Convert between Sequence-ish types and maps

src/with_prefix.rs
`format!("{}{}", a, b)` is a very slow method of concatenating strings. See benchmark: https://gist.github.com/peterjoel/97431103893703e81926ae9bd8f768c5#file-results-txt-L2
=> Improve performance of applying prefix

src/chrono.rs, tests/chrono.rs
=> Add support for chrono::Duration

serde_with_macros/src/lib.rs, serde_with_macros/src/utils.rs, serde_with_macros/tests/compile-fail/skip-none-always.stderr, serde_with_macros/tests/compiler-messages.rs
* Use as error location the field which causes the error instead of only the proc-macro location
* Allow reporting errors for all fields by merging them into one error.
=> Impove proc-macro error handling

src/de/impls.rs, src/de/mod.rs, src/ser/impls.rs, src/ser/mod.rs, src/utils.rs
* Add documentation to the `de` and `ser` modules.
* Expose the types `SerializeAsWrap` and `DeserializeAsWrap`. These
types, or similar ones, are necessary to implement `SerializeAs` for
container types, as the wrapper allows to change how the inner types
get serialized.
* Add documentation to the traits `SerializeAs` and `DeserializeAs`.
=> Improve documentation for serde_as types and traits

Cargo.toml, tests/chrono.rs, tests/hex.rs, tests/json.rs, tests/utils.rs
Replace the #![cfg()] with required-features in Cargo.toml
=> Cleanup cfg features for tests

README.md, src/lib.rs, src/rust.rs, src/ser/mod.rs
Explain some common use cases for this crate.
Show better examples.
Show the new serde_as annotation.
=> Update the entry point of the crate documentation

serde_with_macros/src/lib.rs
Add the undocumented `allow_unknown_fields` option to the darling derive.
This allows to parse also unknown fields, which we need for serde, since we cannot control how and when serde might add new attributes.
Fixes #140
=> Fix #140: allow parsing unknown fields in darling proc-macro part

serde_with_macros/src/lib.rs, serde_with_macros/tests/compile-fail/serde_as.rs, serde_with_macros/tests/compile-fail/serde_as.stderr
Refactor the serde_as macro code to pass through the darling::Errors
such that the code no longer panics and produces nice error messages.
Add UI test which shows the error messages.
=> Fix #139: Do not panic on darling errors

Cargo.toml, serde_with_macros/CHANGELOG.md, serde_with_macros/Cargo.toml, serde_with_macros/src/lib.rs
Release a new version with a serde_as macro which is actually usable.
* Update Changelog
=> Release serde_with_macros 1.2.0-alpha.2

.codecov.yml
https://community.codecov.io/t/github-check-not-properly-handling-subsets-of-files/1853
=> codecov: Remove target from tests, as this currenlty uses the global coverage and not the test coverage

src/de/impls.rs, src/lib.rs, src/rust.rs
Use the `GoodOrError` enum from the legacy implementation to correctly
deserialize lists and maps. Otherwise the deserializer gets stuck on
invalid syntax because the value is not properly consumed.
Document `DefaultOnError` and put a link to the serde_as version on the legacy item.
=> Fix and document DefaultOnError

Cargo.toml, tests/utils.rs
The tests/utils.rs functions show the wrong location when the attribute
is not given. In 1.46 the attribute will be stable so can be used.
Use rustversion as a dev-dependency to apply #[track_caller] when
running 1.46 or later.
=> Improve test UX a bit by using #[track_caller] when available

Cargo.toml, README.md, serde_with_macros/src/lib.rs, src/lib.rs, tests/version_numbers.rs
The links were pointing to the * version which equals to the latests.
But the latest version might now have the same types as the version in
master.
This already caused frustration with the user guide not being available
in #137.
Fixes #137
=> Ensure that docs.rs links always point to the current version

serde_with_macros/src/lib.rs, serde_with_macros/tests/deserialize_fromstr.rs, serde_with_macros/tests/serialize_display.rs, src/lib.rs, src/rust.rs
The crate already supports using Display and FromStr for de/serializing,
but only using the with-attribute and the serde_as system. Implementing
De/Serialize still required manual code.
This derive closes that gap.
Fixes #86
Closes https://github.com/serde-rs/serde/issues/908
=> Add derive macros to implement De/Serialize based on Display and FromStr

.github/workflows/audit.yaml, .github/workflows/ci.yaml, bors.toml, serde_with_macros/tests/compiler-messages.rs
* Run on more Rust versions. Include not only the minimal supported Rust
version but all versions in 5 step increments.
* Run the build_and_test phase directly instead of waiting for clippy
and rustfmt. That should improve overall build times.
* Add a Test status action. This only succeeds if all other tests
succeed and is mainly for bors
* Run CI once every week
* Simplify bors script using the new status and add the audit action
also as a requirement.
=> Improve CI parts

Cargo.toml, tests/chrono.rs, tests/hex.rs, tests/json.rs, tests/rust.rs, tests/utils.rs, tests/with_prefix.rs
Add `*_expect` versions to `tests/utils.rs` to make use of `expect_test`.
Rewrite many of the old tests (not doc-tests) to use the functions from utils and also the `expect` variants.
=> Improve test framework

CHANGELOG.md, src/duplicate_key_impls/first_value_wins.rs, src/duplicate_key_impls/last_value_wins.rs, src/duplicate_key_impls/mod.rs, src/rust.rs, tests/rust.rs
The first is already the default behavior of serde, so it can be
deprecated.
Instead add a module which does the opposite of serde's behavior.
=> Deprecate `sets_first_value_wins` in favour of `sets_last_value_wins`

.github/workflows/ci.yaml
89aec68c9962de062acb1ac90ec6e36ef999f552
This commit should not have passed CI, yet it did.
=> The "Test result" check is wrongly successful.

serde_with_macros/src/lib.rs, serde_with_macros/tests/no_imports_or_clobbering.rs
I often like to alias `type Result<T> = std::result::Result<T, MyError>`.
Unfortunately this doesn't work with the proc-macros as they assume `Result` == `std::result::Result`. The fix is to fully namespace them.
=> namespace Result to std::result

serde_with_macros/src/lib.rs, serde_with_macros/tests/deserialize_fromstr.rs
I hit a problem when using  the `DeserializeFromStr` macro along with the `csv` crate, namely that `csv` tries to call `visit_bytes` to deserialize each column, and the macro does not implement this method. This PR adds it.
I have added a slightly convoluted test case which creates a `Deserializer` which can only handle bytes. This was necessary as the `serde_json` crate used elsewhere is 'too clever' for this test.
=> deserialize macro implements visit_bytes

.github/workflows/ci.yaml, CHANGELOG.md, Cargo.toml
This tests that we do not accidentially depend on serde's derive
feature or other features again.
=> Add derive feature and ensure to not accidentially add dependencies on other features

Cargo.toml, serde_with_test/Cargo.toml, serde_with_test/tests/flattened_maybe.rs, src/flatten_maybe.rs
Due to the derive inside I found it impossible to make it crate name agnostic,
since I would need to specify something like
#[serde(crate = $crate"::serde")]
which does not work since that requires a string literal.
Providing a string literal to flattened_maybe also doesn't work, since then
the uses of Deserialize etc cannot work.
Part of #207
=> Update `flattened_maybe` to better work with renamed crates

serde_with_macros/src/lib.rs, serde_with_test/tests/serde_as_crate_path.rs
Part of #207.
The test could probably be expanded to cover more codegen paths.
=> `serde_as` alternate crate path: add `crate` attribute arg, use path for field attribute generation

serde_with_macros/src/lib.rs, src/guide/serde_as.md
=> Move proc macro re-exporting example to `guide/serde_as.md`

README.md, src/guide.md, src/guide/serde_as.md, src/lib.rs
1. Describe how to do this with an existing module compatible with the
#[serde(with = "...")] annotation.
Based on the discussion in #225.
2. Based on serde's remote derive. This has a similar use case.
Closes #225
=> Better document how to use `SerializeAs` with types from other crates

serde_with_macros/src/lib.rs, tests/serde_as_macro.rs
This used to cause a compile error as the field attributes did not all get removed.
=> Fix: Correctly handle when the serde_as field attr is split into multiple parts

CHANGELOG.md, src/lib.rs, src/ser/impls.rs, src/ser/mod.rs, tests/serde_as.rs, tests/utils.rs
This PR relaxes various serialization related trait bounds, for example in `As`, `Same`, or `SerializeAs` to allow for unsized types.
It then adds `SerializeAs` implementations for references and for slices.
This allows to write code like:
```rust
#[serde_as]
#[derive(Serialize)]
struct S<'a>
#[serde_as(as = "&[DisplayFromStr]")]
slice: &'a [u32],
}
```
bors r+
=> Add SerializeAs implementation for references and support unsized types

.github/workflows/ci.yaml, src/rust.rs
The `--all-targets` flag for `cargo test` actually DISABLES doctests.
Doctests should of course be run, so removing the flag from the CI scrips.
There is a bug report for cargo about this behavior:
https://github.com/rust-lang/cargo/issues/6669
This fixes the changes done in #235 / 9a6c3bf9e5fdbf6c76a27534ee250628acf8e168.
=> Do not call `cargo test` with `--all-targets`

serde_with_macros/CHANGELOG.md, serde_with_macros/src/lib.rs
Rely more on the quote! macro (quasi-quoting) and remove cases of
string-interpolation and string parsing.
bors r+
=> Cleanup assembling and parsing of attributes during `serde_as` processing.

serde_with_test/tests/serde_as_crate_path.rs
Sort inert attributes after the derive.
https://github.com/rust-lang/rust/issues/79202
bors r+
=> Fix nightly warning legacy_derive_helpers

serde_with_macros/CHANGELOG.md, serde_with_macros/src/lib.rs, serde_with_macros/tests/compile-fail/serde_as.stderr
The attributes will no longer be stripped during proc-macro processing.
Instead, a private derive macro is applied to the struct/enum which captures them and makes them inert, thus allowing compilation.
This should have no effect on the generated code and on the runtime behavior.
It eases integration of third-party crates with `serde_with`, since they can now process the `#[serde_as(...)]` field attributes reliably.
Before this was impossible for derive macros and lead to akward ordering constraints on the attribute macros.
Previous discussion in: https://github.com/jonasbb/serde_with/discussions/260
@Lehona Could you please check if this solves your issue?
=> Change processing of `#[serde_as(...)]` attributes on fields.

CHANGELOG.md, Cargo.toml, README.md, serde_with_macros/CHANGELOG.md, serde_with_macros/Cargo.toml, serde_with_macros/src/lib.rs, src/lib.rs
Upgrade serde_with_macros to 1.4.0.
Upgrade serde_with to 1.6.3 to pull in the new serde_with_macros version.
bors r+
=> Bump Versions

CHANGELOG.md, Cargo.toml, README.md, serde_with_macros/CHANGELOG.md, serde_with_macros/Cargo.toml, serde_with_macros/src/lib.rs, serde_with_macros/tests/serde_as_issue_267.rs, src/lib.rs
This broke in 1.4.0 due to removing the check if there are any `serde_as` attributes.
Add a test case for a struct with an un-annotated field.
Fixes #267
Bump versions to release bugfix.
bors r+
=> Fix compilation with serde_as if there is a field without annotation

Cargo.toml
Marcin Kaźmierczak devised the `SerializeAs` and `DeserializeAs` traits.
bors r+
=> Better acknowledge Marcin Kaźmierczak as co-author

.github/workflows/ci.yaml
1.50 is another version divisible by 5.
It is also the last version before const generics.
bors r+
=> Add Rust 1.50 to the Rust version tested on CI

CHANGELOG.md, Cargo.toml, src/de/const_arrays.rs, src/de/impls.rs, src/guide/serde_as.md, src/lib.rs, src/ser/const_arrays.rs, src/ser/impls.rs, tests/serde_as.rs
The `Bytes` type is heavily inspired by `serde_bytes` and ports it to the
serde_as system.
```rust
#[serde_as(as = "Bytes")]
value: Vec<u8>,
```
Compared to `serde_bytes` these improvements are available
1. Integration with the `serde_as` annotation.
/cc https://github.com/serde-rs/bytes/issues/14
2. Implementation for arrays of arbitrary size (Rust 1.51+).
/cc https://github.com/serde-rs/bytes/issues/26
=> Add a `Bytes` type for more efficient byte sequences

CHANGELOG.md, Cargo.toml, src/de/impls.rs, src/formats.rs, src/guide/serde_as.md, src/lib.rs, src/ser/impls.rs, tests/serde_as.rs
```rust
#[serde_as(as = "OneOrMany<_>")]
cities: Vec<String>,
```
This allows to deserialize from either `cities: "Berlin"` or `cities: ["Berlin", "Paris"]`.
The serialization can be configured to always emit a list with `PreferMany` or emit a single element with `PreferOne`.
This is a features which keeps getting asked:
* https://github.com/serde-rs/serde/issues/889
* https://github.com/serde-rs/serde/issues/1891
* https://github.com/serde-rs/serde/issues/1907
* https://www.reddit.com/r/rust/comments/l3exvd/question_how_to_deserialize_either_a_vec_of_enum/
=> Add `OneOrMany` type which deserializes a `Vec` from a list or a single element.

.vscode/settings.json, CHANGELOG.md, Cargo.toml, README.md, serde_with_macros/src/lib.rs, src/lib.rs
Bump the version to 1.7.0.
This includes all changes for the const-generics array support.
=> Bump version to 1.7.0

CHANGELOG.md, src/rust.rs, tests/rust.rs
The existing bound on `btreemap_as_tuple_list` and
`hashmap_as_tuple_list` are more restrictive than necessary. In fact,
both of them can be merged by using the `IntoIterator`,
`ExactSizeIterator`, and `FromIterator` traits.
This now provides support types besides `HashMap` and `BTreeMap`.
The old names are still available but are marked as deprecated.
The replacement is the new `map_as_tuple_list` module.
=> Improve and merge the `btreemap_as_tuple_list` and `hashmap_as_tuple_list` modules

CHANGELOG.md, src/chrono.rs, src/de/impls.rs, src/ser/impls.rs, tests/chrono.rs
This implements the range of milli, micro, and nano variants for
TimestampSeconds and DurationSeconds types.
This was left missing from #194.
The new implementations are still missing tests.
Closes #194
=> Add the missing `Timestamp*` and `Duration*` implementations for chrono types

src/hex.rs
I did what I thought you described on #300.
Please let me know if there are any issues.
Closes #300
=> Add array deserialization support to `Hex`

.github/workflows/ci.yaml
Version 1.4.0 is broken and cannot be used anymore, since it breaks the build due to a checksum mismatch error.
https://github.com/codecov/codecov-action/issues/289
=> Bump codecov action to 1.4.1

serde_with_macros/CHANGELOG.md, serde_with_macros/src/lib.rs
=> Describe how the serde_as macro works on a high level

serde_with_macros/CHANGELOG.md, serde_with_macros/src/lib.rs, serde_with_test/tests/derive_display_fromstr.rs, serde_with_test/tests/flattened_maybe.rs, serde_with_test/tests/serde_as_crate_path.rs
Properly name all types and traits in the derive macros such that they do not conflict with the environment where they are used.
bors r+
=> Fix proc-macros were relying on the prelude to be available

CHANGELOG.md, src/de/impls.rs, src/guide/serde_as.md, src/lib.rs, src/ser/impls.rs, tests/serde_as/frominto.rs, tests/serde_as/lib.rs, tests/utils.rs
This PR is supposed to show that the conversions can be implemented without adding new functionality to the derive macro.
If there is sufficient interest this can be finished into a full feature.
Missing:
=> Add converters for (Try)From/Into similar to serde-rs/serde#1623

src/flatten_maybe.rs
=> Fix TODO for flattened_maybe bby using a `literal` macro matcher

CHANGELOG.md, src/de/impls.rs, tests/serde_as/lib.rs
The docs for `NoneAsEmptyString` are wrong. For deserialization `for<'a> From<&'a str>` is used instead of `FromStr`.
In my case, only `FromStr` is available, so I have to use `rust::string_empty_as_none` instead. Those docs advertise identical functionality using `NoneAsEmptyString`, so that advertisement either needs to be removed or `NoneAsEmptyStrings` functionality adjusted.
Which would you prefer?
PS: Thanks for this awesome project! :)
=> NoneAsEmptyString: Deserialize using FromStr

src/serde_conv.rs
With `String` as `t`, `&String` would trigger [`clippy::ptr_arg`](https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg).
What do you think?
=> `serde_conv`: Allow `clippy::ptr_arg`

CHANGELOG.md, src/de/const_arrays.rs, src/lib.rs, src/ser/const_arrays.rs
Currently `Bytes` (added in #277) supports some const size array types (e.g. `[u8; N]` and `Box<[u8; N]>`)
but not others (e.g. `&[u8; N]` and `Cow<'_, [u8; N]>`).
This pull request implements `Bytes` support for `&[u8; N]` and `Cow<'_, [u8; N]>`
This bring parity between dynamic and const sized types.
| Sizing  | Owned          | Borrowed      | Cow                   | Box               |
| ------- | -------------- | ------------- | --------------------- | ----------------- |
| Const   | ✅ `[u8; N]`   | ❌ `&[u8; N]` | ❌ `Cow<'_, [u8; N]>` | ✅ `Box<[u8; N]>` |
| Dynamic | ✅ `Vec<u8>`\* | ✅ `&[u8]`    | ✅ `Cow<'_, [u8]>`    | ✅ `Box<[u8]>`    |
| Sizing  | Owned          | Borrowed      | Cow                   | Box               |
| ------- | -------------- | ------------- | …
=> Bytes const size borrowed arrays

serde_with_macros/tests/compiler-messages.rs
Rust beta has more detailed error messages than stable, making the test fail.
bors r+
=> Ignore compiler-messages test on beta

Cargo.toml, README.md, src/lib.rs
* Add doc_cfg annotations
* Generate links to definitions on the src pages.
Also document in the README/main doc page how to use `serde_as` for large arrays/const generic arrays.
bors +
=> Make use of nightly features to improve the documentation on docs.rs

.github/workflows/ci.yaml, CHANGELOG.md, serde_with_macros/src/lib.rs, serde_with_test/tests/derive_display_fromstr.rs, serde_with_test/tests/flattened_maybe.rs, src/lib.rs, src/with_prefix.rs, tests/serde_as/lib.rs, tests/serde_as/map_tuple_list.rs, tests/utils.rs
The dev-dependency bitflags changed the MSRV, so bump it here too to make CI pass.
=> Bump MSRV to 1.46

src/rust.rs
I noticed these comments in #345.
The change in tuple_list_is_map is simply smaller code, but otherwise equivalent.
The change in seq_display_fromstr introduces collect_str to avoid heap allocating a temporary copy of every string object in the sequence.
=> Use collect_seq and collect_map where applicable v2

serde_with_test/tests/flattened_maybe.rs, src/flatten_maybe.rs
Lift the restriction on the `flattened_maybe!` macro, which required the `serde_with` crate to be available under this name.
By use-ing `$crate::serde` it is possible to use the path in the crate attribute of serde.
Directly placing the `$crate` into the serde attribute does not work.
bors merge
=> Lift restriction `flattened_maybe!` about `serde_with`

.github/workflows/ci.yaml
But using an `=` sign works.
https://github.com/xd009642/tarpaulin/issues/819
bors merge
=> `--test-threads 1` is broken on tarpaulin 0.18.1

src/guide.md, src/guide/serde_as.md, src/guide/serde_as_transformations.md, src/lib.rs
* Move the list of transformations into its own file.
* Make better use of multiple heading levels.
* Explain that conditional compilation with serde_as is currently not
working. Explain workaround.
Closes #355
=> Restructure the serde_as documentation

.github/workflows/ci.yaml
After reading
https://matklad.github.io//2021/09/04/fast-rust-builds.html#ci-workflow
implement some of the CI workflow recommendations.
* Split testing into a `--no-run` step and a testing step, to be able to
get timing for build and execution.
* Also add `--no-fail-fast` during execution.
* Disable debuginfo during CI. Do this via environment variables instead
of modifying Cargo.toml
bors merge
=> Update CI pipeline

README.md, src/lib.rs
The docs.rs is no longer useful, since it now just forwards to
shields.io and contains no useful information, i.e., the current version
on docs.rs.
https://github.com/rust-lang/docs.rs/pull/1362
bors merge
=> Remove docs.rs badge, since it no longer shows the current version

src/rust.rs, tests/rust.rs
Deserialize `OptionStringEmptyNone` from Some and None too, not just from unit
`visit_some` and `visit_none` implemented for `OptionStringEmptyNone`'s Visitor
unit tests for `string_empty_as_none` added
=> unit tests for string_empty_as_none

serde_with/CHANGELOG.md, serde_with/Cargo.toml, serde_with/src/base64.rs, serde_with/src/formats.rs, serde_with/src/guide/feature_flags.md, serde_with/src/guide/serde_as_transformations.md, serde_with/src/lib.rs, serde_with/tests/base64.rs
Create a new optional module to house the code.
Add a new `CharacterSet` trait, which is used to encode the different
character sets with multiple unique types.
Add a basic test.
Missing:
Closes #350
=> Base64 Support

CONTRIBUTING.md, serde_with/src/lib.rs, serde_with_macros/src/lib.rs
This makes local development easier, since warnings do not fail
compilation.
On CI all warnings are denied anyway, so it will not pass.
Closes #386 
bors merge
=> Turn deny lints into warn

serde_with/CHANGELOG.md, serde_with/src/chrono.rs, serde_with/src/guide/serde_as_transformations.md, serde_with/src/lib.rs, serde_with/tests/chrono.rs
=> Support `chrono::NaiveDateTime` for `TimestampSeconds` and variants

.github/workflows/audit.yaml, .github/workflows/ci.yaml, .github/workflows/publish-crates-io.yaml
Most actions in the actions-rs organizations were last updated more than a year ago meaning they are effectively unmaintained.
Remove the actions and call rustup and cargo manually.
Switch to `softprops/action-gh-release` for creating releases, since the current one is no longer maintained.
=> Remove unmaintained actions

serde_with/Cargo.toml
The new 1.2.3 version works with the current MSRV
bors r+
=> Revert "Pin expect-test to an older version to  fix MSRV 1.46 tests"

serde_with/src/content/mod.rs, serde_with/src/content/ser.rs, serde_with/src/lib.rs
This copies and improves on the `ser::Content` type of `serde`. 
The code mostly corresponds to this module.
https://github.com/serde-rs/serde/blob/55a7cedd737278a9d75a2efd038c6f38b8c38bd6/serde/src/private/ser.rs#L338-L997
Compared to the `serde` code, the code is extended to support 128-bit integers and the human readable flag.
This crate targets a MSRV larger than 1.40, so 128-bit integers are supported on all targets.
The human readable support is important to make round-trips as lossless as possible, e.g., when serializing `IpAddr` with `rmp`.
This will become the basis of #375
=> Include a local copy of `serde`'s `Content` type

serde_with/CHANGELOG.md, serde_with/src/de/impls.rs, serde_with/tests/serde_as/collections.rs, serde_with/tests/serde_as/lib.rs
https://users.rust-lang.org/t/recursive-serde-deserialize-with-definition/70865/3
A user reported that `FnvHashSet` could not be deserialized in
combination with `serde_as`.
This commit adds the necessary bound on the hasher and adds a test to
prevent regressions.
=> Ensure that `HashSet` can be used with custom hashers

serde_with_macros/CHANGELOG.md, serde_with_macros/src/lib.rs, serde_with_macros/src/utils.rs, serde_with_test/tests/derive_display_fromstr.rs
The derives did not take into account that types can have generics. Ensure that lifetime and type generics are added to the generated impls. Add new tests to `serde_with_test` to prevent regressions.
=> Allow generics for `SerializeDisplay` and `DeserializeFromStr` derives

serde_with/src/lib.rs
The new lint `clippy::only_used_in_recursion` is buggy when used in traits.
https://github.com/rust-lang/rust-clippy/issues/8560
=> Fix wrong clippy warning

.devcontainer/Dockerfile
clippy in the nightly version comes in handy to run more lints and be
able to debug the recurring nightly problems.
cargo-tarpaulin is quite heavy to build and not that often needed, so
it can be omitted and installed on demand.
Install crates with `--locked` to avoid potential breakage.
bors merge
=> Rework pre installed tools in the devcontainer

serde_with_macros/Cargo.toml, serde_with_macros/src/lib.rs
This relies on a newer `darling` version.
Closes #423
bors merge
=> Provide better error messages for type parse failures

.github/workflows/publish-crates-io.yaml
The YAML string was accidentially not a newline preserving string.
bors merge
=> Fix syntax error in the release script

serde_with/Cargo.toml, serde_with/src/duplicate_key_impls/error_on_duplicate.rs, serde_with/src/duplicate_key_impls/last_value_wins.rs, serde_with/src/guide/feature_flags.md
Add optional support for `indexmap` to
- `sets_duplicate_value_is_error`
- `maps_duplicate_key_is_error`
- `sets_last_value_wins`
Signed-off-by: Joe Grund <jgrund@whamcloud.io>
=> Add support for `indexmap`

serde_with/Cargo.toml, serde_with/src/de/impls.rs, serde_with/src/duplicate_key_impls/first_value_wins.rs, serde_with/src/ser/impls.rs, serde_with/tests/indexmap.rs
During the tests a missing implementation of `DuplicateInsertsFirstWinsMap` was noticed, but is now included.
`indexmap` was also missing the `serde-1` feature flag.
bors merge
=> Add tests for IndexMap and IndexSet

.github/workflows/scorecards-analysis.yml
Without a way to supress analysis results more permanently the security
tab becomes too noisy. Either the action needs to allow an allowlist or
the GitHub UI needs to be better in permanently supressing lines.
The biggest annoyance is that each change to a action tag will trigger
a new warning, even if the same line was ignored before.
https://github.com/ossf/scorecard-action/issues/143
=> Disable the OSSF Scorecard Action

.github/workflows/ci.yaml, serde_with/CHANGELOG.md, serde_with/Cargo.toml, serde_with/src/guide/feature_flags.md, serde_with/src/guide/serde_as_transformations.md, serde_with/src/lib.rs, serde_with/src/time_0_3.rs, serde_with/src/utils/duration.rs, serde_with/tests/time_0_3.rs, serde_with_macros/Cargo.toml, serde_with_test/Cargo.toml, serde_with_test/tests/derive_display_fromstr.rs, serde_with_test/tests/flattened_maybe.rs
Add support for the `time` crate v0.3.
* Convert `time::Duration` with `Duration*Second`.
* Convert `time::OffsetDateTime` and `time::PrimitiveDateTime` with `Timestamp*Seconds`.
* Turn `Rfc2822` and `Rfc3339` into conversion type, such that they can be used inside collections.
* Add tests for the new functionality
Todo:
=> Add support for `time` v0.3 types

.github/workflows/ci.yaml, Cargo.toml, serde_with/Cargo.toml, serde_with/src/de/mod.rs, serde_with/src/guide/serde_as_transformations.md, serde_with/src/hex.rs, serde_with/src/lib.rs, serde_with/src/ser/const_arrays.rs, serde_with/src/ser/mod.rs, serde_with/tests/serde_as/lib.rs, serde_with/tests/serde_as/map_tuple_list.rs
The MSRV got updated and this commit removes old code. Pre const-generic code could all be removed. Some further older entries could also be removed.
This makes `rustversion` a dev-dependency, since runtime changes are not necessary anymore.
Closes #451
bors merge
=> Cleanup code for pre-1.53 versions

serde_with/CHANGELOG.md, serde_with/src/de/impls.rs, serde_with/src/guide/serde_as_transformations.md, serde_with/src/lib.rs, serde_with/src/ser/impls.rs, serde_with/tests/serde_as/lib.rs
=> Add `BoolFromInt` adapter

serde_with/CHANGELOG.md, serde_with/tests/serde_as/serde_as_macro.rs, serde_with_macros/CHANGELOG.md, serde_with_macros/src/lib.rs
Using `#[serde_as]` on a field of type `Option` changes the behavior, in that the field can no longer be missing.
This often times was unexpected and lead to confusion (e.g., #183, #185, #311, #417).
Now if both the field and the transformation type are `Option` the `#[serde(default)]` attribute is added. `Option`s are identified by exact text matches and these variants are supported:
* `Option`
* `std::option::Option`, with or without leading `::`
* `core::option::Option`, with or without leading `::`
If a `default` attribute already exists nothing happens. This new behavior can be suppressed by using `#[serde_as(no_default)]` on the field. If the transformation type is not `Option`, e.g., like `NoneAsEmptyString`, nothing happens either.
Closes #185
=> Simplify `serde_as` handling around `Option`s

.github/workflows/ci.yaml, serde_with/Cargo.toml, serde_with/src/de/impls.rs, serde_with/src/duplicate_key_impls/error_on_duplicate.rs, serde_with/src/duplicate_key_impls/first_value_wins.rs, serde_with/src/duplicate_key_impls/last_value_wins.rs, serde_with/src/formats.rs, serde_with/src/guide/feature_flags.md, serde_with/src/lib.rs, serde_with/src/rust.rs, serde_with/src/ser/impls.rs, serde_with/src/utils.rs, serde_with/src/utils/duration.rs
* Introduce new `alloc` and `std` features
* Feature gate all imports and implementations
Further Todos:
* Documentation updates like the new features
* Check which features depend on `alloc` and `std` and enable these if necessary.
Part of #435
=> Support `no_std` for `serde_with` Take 2

CONTRIBUTING.md, serde_with/CHANGELOG.md, serde_with/src/de/mod.rs, serde_with/src/guide/serde_as.md, serde_with/src/guide/serde_as_transformations.md, serde_with/src/json.rs, serde_with/src/ser/mod.rs
* Previously forgot to remove `json::nested` which can be replaced with `json::JsonString`.
* Some typos.
* Update the guide to include the new rules for optional fields.
bors r+
=> Some more cleanups

serde_with/Cargo.toml, serde_with/src/chrono_0_4.rs, serde_with/src/de/impls.rs, serde_with/src/duplicate_key_impls/error_on_duplicate.rs, serde_with/src/duplicate_key_impls/first_value_wins.rs, serde_with/src/duplicate_key_impls/last_value_wins.rs, serde_with/src/guide/feature_flags.md, serde_with/src/lib.rs, serde_with/src/ser/impls.rs, serde_with/src/utils/duration.rs, serde_with/tests/chrono_0_4.rs, serde_with/tests/indexmap_1.rs
* Rename `chrono` to `chrono_0_4`
* Rename `indexmap` to `indexmap_1`
* Rename the `chrono` module.
* Add aliases for the old names and module, such that no changes in other crates should be necessary.
=> Rename crate feature to indicate the specific versions

serde_with/CHANGELOG.md, serde_with/src/guide/serde_as_transformations.md, serde_with/src/json.rs, serde_with/tests/json.rs
This allow nested application of `serde_as` logic on the inner value.
```rust
// Rust
value: BTreeMap<[u8; 2], u32>,
// JSON
{"value":"[[\"[1,2]\",3],[\"[4,5]\",6]]"}
```
Closes #485
bors r+
=> Make the `JsonString` smarter

serde_with/CHANGELOG.md, serde_with/Cargo.toml, serde_with/src/guide/serde_as_transformations.md, serde_with/src/time_0_3.rs, serde_with/tests/time_0_3.rs
This adds `serde_as` support for `Iso8601`.
bors r+
=> The time crate added support for `Iso8601` as a well-known format.

.cargo/audit.toml, serde_with/Cargo.toml
Chrono now - 0.4.20 - has localtime_r RIR that has addressed the past security issue around it :partying_face:
We've updated here:
https://rustsec.org/advisories/RUSTSEC-2020-0159.html
=> Bump fixed chrono 0.4.20

README.md, serde_with/CHANGELOG.md, serde_with/src/lib.rs, serde_with_macros/CHANGELOG.md, serde_with_macros/src/lib.rs, serde_with_macros/tests/compile-fail/serde_as-enum-variant-499.rs, serde_with_macros/tests/compile-fail/serde_as-enum-variant-499.stderr
Change the serde_as macro to warn on serde_as attributes on enum variant
fields. They are unsupported (in contrast to serde_derive), so showing
an error is better and avoids confusion when migrating.
Also update the main examples to include an enum.
Closes #499
=> Better handle serde_as on enum variants #499

.cargo/audit.toml, .github/workflows/audit.yaml
Use a maintained action for auditing Rust dependencies.
Ignore advisories:
* RUSTSEC-2021-0139: ansi_term is Unmaintained
Inactionable, since this is a transitive dependency of pretty_assertions
Only used in test code.
* RUSTSEC-2022-0048: xml-rs is Unmaintained
Inactionable, since this is a transitive dependency of serde-xml-rs
Only used in test code.
Closes #504
Closes #508
=> Update audit handling and ignore advisories

README.md, serde_with/src/lib.rs, serde_with/tests/version_numbers.rs
=> Recommend `cargo add` in the install instructions instead of a toml snippet

serde_with/Cargo.toml, serde_with/src/base64.rs, serde_with/src/chrono_0_4.rs, serde_with/src/content/ser.rs, serde_with/src/de/impls.rs, serde_with/src/de/mod.rs, serde_with/src/duplicate_key_impls/error_on_duplicate.rs, serde_with/src/duplicate_key_impls/first_value_wins.rs, serde_with/src/duplicate_key_impls/last_value_wins.rs, serde_with/src/enum_map.rs, serde_with/src/flatten_maybe.rs, serde_with/src/formats.rs, serde_with/src/hex.rs, serde_with/src/json.rs, serde_with/src/lib.rs, serde_with/src/rust.rs, serde_with/src/ser/impls.rs, serde_with/src/ser/mod.rs, serde_with/src/serde_conv.rs, serde_with/src/time_0_3.rs, serde_with/src/utils.rs, serde_with/src/utils/duration.rs, serde_with/src/with_prefix.rs, serde_with_macros/src/lib.rs
Instead import names through the `serde_with` crate.
This should make the code more portable by avoiding references to std.
The `macro` feature still depends on `std`, but this might be removable
in the future.
=> Avoid absolut import in macros and always import through the `serde_with` crate

README.md, serde_with/src/lib.rs
Rustexplorer is a playground similar to play.rust-lang.org but with more crates like this one.
bors r+
=> Replace binder link with rustexplorer

README.md, serde_with/CHANGELOG.md, serde_with/Cargo.toml, serde_with/src/lib.rs, serde_with_macros/CHANGELOG.md, serde_with_macros/Cargo.toml, serde_with_macros/src/lib.rs
=> Bump versions to v2.0.1

serde_with/src/de/impls.rs, serde_with/src/lib.rs
=> Fix typo in `BorrowCow` documentation and use `deserialize_string`

.devcontainer/devcontainer.json, .vscode/settings.json
Modernize the devcontainer config.
Use proper fields instead of runArgs where possible.
Put the vscode stuff under the new `customizations` field.
Use the repository based feature names.
bors r+
=> Update devcontainer config

serde_with/CHANGELOG.md, serde_with/src/chrono_0_4.rs, serde_with/tests/chrono_0_4.rs, serde_with_macros/CHANGELOG.md, serde_with_macros/Cargo.toml, serde_with_macros/src/apply.rs, serde_with_macros/src/lib.rs, serde_with_macros/tests/apply.rs
This `apply` proc-macro takes a list of type patterns and a list of attributes for each. On each field where the type matches, the list of attributes will be added to the existing field attributes.
```rust
#[serde_with::apply(
Option => #[serde(default)] #[serde(skip_serializing_if = "Option::is_none")],
Option<bool> => #[serde(rename = "bool")],
)]
#[derive(serde::Serialize)]
struct Data {
a: Option<String>,
b: Option<u64>,
c: Option<String>,
d: Option<bool>,
}
```
The `apply` attribute will expand into this, applying the attributs to the matching fields:
```rust
#[derive(serde::Serialize)]
struct Data {
#[serde(default)]
#[serde(skip_serializing_if = "Option::is_none")]
a: Option<String>,
#[serde(default)]
#[serde(skip_serializing_if = "Option::is_none")]
b: Option<u64>, …
```
=> Implement `apply` attribute #85

serde_with_macros/src/lib.rs
**Good to know:**
- `cargo +nightly fmt` formatted the comments with long lines
- I've made this PR because using `SerializeDisplay` on a struct that was generic over `S` (ex `struct MyStruct<S: Borrow<str>> { ... }` would fail as the struct generic type would conflict with the serialize generic `S`
=> Rename generics in macro outputs to reduce conflicts

serde_with/src/de/impls.rs, serde_with/src/guide/serde_as_transformations.md, serde_with/src/lib.rs, serde_with/src/ser/impls.rs, serde_with/src/utils.rs, serde_with/tests/serde_as/lib.rs, serde_with/tests/serde_as/map_tuple_list.rs, serde_with_macros/CHANGELOG.md
The behavior is not new, but already present using `BTreeMap`/`HashMap` or `Vec`.
However, the new types `Map` and `Seq` are also available on `no_std`, even without the `alloc` feature.
Closes #527 
bors r+
=> Create `Map` and `Seq` types to map to tuple list conversion

README.md, serde_with/src/lib.rs
I think https://github.com/jonasbb/serde_with/pull/277 can be more promoted. :)
As I wrote the current status of serialization of const generics like bytes (https://github.com/solana-labs/solana/pull/29196#discussion_r1052189935), i think `"Bytes"` is best solution so far.
@jonasbb hey, this functionary saved us. however it took a while to spot this. I think `Bytes` can be promoted. :)
=> Mention "Bytes" on README.md and lib.rs

.github/workflows/publish-crates-io.yaml, serde_with/CHANGELOG.md, serde_with/Cargo.toml, serde_with/tests/version_numbers.rs
This pins serde_with_macros to a single version. This simplifies updates and publishing. It also ensures that the macros dependency always gets updated when the main crate does.
=> Use synchronized version numbers for serde_with and serde_with_macros

README.md, serde_with/CHANGELOG.md, serde_with/Cargo.toml, serde_with/src/lib.rs, serde_with/tests/version_numbers.rs, serde_with_macros/CHANGELOG.md, serde_with_macros/Cargo.toml, serde_with_macros/src/apply.rs, serde_with_macros/src/lib.rs, serde_with_macros/tests/serde_as_issue_538.rs, serde_with_macros/tests/version_numbers.rs
The macro had a problem with invisible token groups, which can stem from macro_rules expansion. The token groups should be treated mostly transparent. This is now achieved by always looking through the groups first before continuing with any other type pattern matching.
Fixes #538
Prepare new release.
bors r+
=> Fix type pattern matching in apply macro

Cargo.toml, serde_with/Cargo.toml, serde_with/src/lib.rs, serde_with_macros/Cargo.toml, serde_with_macros/src/lib.rs, serde_with_test/Cargo.toml
This will simplify updating version numbers, updating links, and creating tags.
bors r+
=> Provide cargo-release configuration

serde_with_macros/tests/skip_serializing_null.rs
=> Fix a needless borrow clippy warning in a test

serde_with/src/rust.rs, serde_with_macros/tests/compiler-messages.rs
And remove an outdated version check.
bors r+
=> Document why `double_option` cannot be used in `serde_as`

.github/dependabot.yml
The Cargo.lock file is mainly for a stable CI environment and to prevent
unintended dependency bumps. It does not affect the users of the crate.
Therefore, we can ignore patch version bumps.
bors r+
=> dependabot: Ignore cargo patch versions

serde_with/CHANGELOG.md, serde_with/src/enum_map.rs
=> Mape `EnumMap` better in passing the `human_readable` status through the call stack

serde_with/src/ser/impls.rs
Add new macros like `foreach_map` which expand once for each supported
map type, e.g., `BTreeMap`, `HashMap`, `IndexMap`.
They take another macro as input and pass the map as the first argument.
It is used like `foreach_map!(map_impl);` and
`foreach_map!(map_as_tuple_seq);`.
This also helps for future implementations.
=> Generalize how to implement traits for many collection types.

serde_with/CHANGELOG.md, serde_with/src/de/impls.rs, serde_with/src/lib.rs, serde_with/src/ser/impls.rs
This is a fix for the issue described in: #559
- I added a check to require `target_has_atomic = "ptr"` for imports and implemenations related to `Arc` and `Weak/WeakArc`.
- That should be sufficient to support such targets without requiring new feature flags.
Closes #559
=> Support targets without `alloc::sync`/atomic pointers.

serde_with/CHANGELOG.md, serde_with/src/de/duplicates.rs, serde_with/src/de/mod.rs, serde_with/src/guide/serde_as_transformations.md, serde_with/src/lib.rs, serde_with/src/rust.rs, serde_with/src/ser/duplicates.rs, serde_with/src/ser/mod.rs
This adds `serde_as` compatible versions for these four modules:
`maps_duplicate_key_is_error`, `maps_first_key_wins`,
`sets_duplicate_value_is_error`, and `sets_last_value_wins`.
Missing:
Closes #534
=> Add serde_as compatible versions for duplicate key handling

.pre-commit-config.yaml, README.md, serde_with/src/de/mod.rs, serde_with/src/enum_map.rs, serde_with/src/guide.md, serde_with/src/key_value_map.rs, serde_with/src/lib.rs, serde_with/src/ser/mod.rs, serde_with/src/serde_conv.rs, serde_with/tests/serde_as/key_value_map.rs, serde_with_macros/src/lib.rs
=> Make all uses of the `serde_as` macros require an extra import

serde_with/CHANGELOG.md, serde_with/src/de/impls.rs, serde_with/src/lib.rs, serde_with/src/ser/impls.rs, serde_with/tests/serde_as/map_tuple_list.rs
Generalize the trait bounds of `Seq` to allow for more flexible. Instead of forcing the inner type to be a tuple, take anything convertible to/from a tuple. This can be expressed using the
Closes #565
=> Generalize the trait bounds of `Seq`

serde_with/tests/serde_as/map_tuple_list.rs
Some serializers (e.g. bincode) require a length to serialize a sequence. This code does what `iterator_len_hint` does (called by `collect_seq` in `serde`).
Resolves #570
=> Provide length when serializing sequence

serde_with/src/lib.rs
Highlight what is the default, with an extra sentence and emphasis in
the tables.
Unhide the `std::time::Duration` in the examples.
Closes #575
=> Better explain the default FORMAT for DurationSeconds/TimestampSeconds

README.md, serde_with/src/guide.md, serde_with/src/guide/serde_as.md, serde_with/src/lib.rs
Mention that it is supposed to mirror the type structure of the field
and what the special `_` placeholder means.
This was mentioned as insufficiently explained in #582.
bors r+
=> Explain better how to use serde_as

.cargo/audit.toml
=> ansi_term is no longer a dependency, so we can remove the ignore

serde_with/CHANGELOG.md, serde_with/Cargo.toml, serde_with/src/de/impls.rs, serde_with/tests/serde_as/lib.rs, serde_with/tests/serde_as/pickfirst.rs
Untagged enums do not provide good error messages and likely never will,
given that there are multiple PRs which are just completely ignored
([serde#2376](https://github.com/serde-rs/serde/pull/2376) and
[serde#1544](https://github.com/serde-rs/serde/pull/1544)).
Instead using `content::de` the untagged enums can be replaced by custom
buffering. The error messages for `OneOrMany` and `PickFirst` now look
like this, including the original failure for each variant.
```text
OneOrMany could not deserialize any variant:
One: invalid type: map, expected u32
Many: invalid type: map, expected a sequence
```
```text
PickFirst could not deserialize any variant:
First: invalid type: string "Abc", expected u32
Second: invalid digit found in string
```
The implementations of `VecSkipError` and …
=> Improve error messaged by dropping untagged enums

serde_with/src/content/mod.rs, serde_with_macros/src/lib.rs
proc-macros are badly supported by tarpaulin, leading to mostly
uncovered lines, so we exclude them from the reporting.
The `content` module is copied from `serde` but without extensive tests.
bors r+
=> Tweak the coverage configuration

serde_with/Cargo.toml
`serde::de::value::StringDeserializer::new` was introduced in 1.0.139.
=> Require serde 1.0.139

Cargo.lock, Cargo.toml, serde_with/CHANGELOG.md, serde_with/Cargo.toml, serde_with/src/flatten_maybe.rs, serde_with_macros/CHANGELOG.md, serde_with_macros/Cargo.toml, serde_with_macros/src/apply.rs, serde_with_macros/src/lib.rs, serde_with_macros/tests/compile-fail/serde_as.stderr
Update darling to v0.20 and syn to v2, require serde v1.0.157 (first using syn v2).
This moves all direct dependencies to crates using syn v2.
syn v2 has problems with the `#[serde_as(as = "..")]` style of attributes, since `as` is a keyword and keywords are not allowed in meta attributes. Instead pre-process the token stream to replace all `as` with `r#as` which can be parsed.
Bump thiserror and cxx in the lock file.
Not all crates are using syn v2 yet.
=> Prepare for syn v2

Cargo.lock, serde_with/Cargo.toml, serde_with/src/de/impls.rs
There is a breaking change in 0.8.9
https://github.com/netvl/xml-rs/issues/223
bors r+
=> Pin xml-rs dev-dependency to 0.8.4

serde_with/src/lib.rs
As part of #605 the investigation revealed that the documentation of
`NoneAsEmptyString` was wrong. It specified `AsRef<str>` instead of
`Display` as the trait.
bors r+
=> Fix documentation of `NoneAsEmptyString` to specify `Display` instead of `AsRef<str>`.

.github/workflows/ci.yaml, Cargo.lock, serde_with/CHANGELOG.md, serde_with/Cargo.toml, serde_with/src/guide/serde_as.md, serde_with_macros/Cargo.toml, serde_with_test/Cargo.toml, serde_with_test/tests/serde_as_cfg.rs
=> Update documentation on the use of cfg_eval

serde_with/src/de/impls.rs, serde_with/src/lib.rs, serde_with/src/ser/impls.rs, serde_with/tests/serde_as/fromintoref.rs, serde_with/tests/serde_as/lib.rs
Conversions from references are rare, however a user who controls the implementation of the type, can implement `Into<T> from &'a MyType` and use this to avoid cloning.
=> Add FromIntoRef and TryFromIntoRef

serde_with/src/lib.rs
=> Clarify serialization behavior of Duration* and Timestamp* types

.github/workflows/ci.yaml, Cargo.lock, serde_with/CHANGELOG.md, serde_with/Cargo.toml, serde_with/src/de/duplicates.rs, serde_with/src/de/impls.rs, serde_with/src/duplicate_key_impls/error_on_duplicate.rs, serde_with/src/duplicate_key_impls/first_value_wins.rs, serde_with/src/duplicate_key_impls/last_value_wins.rs, serde_with/src/guide/feature_flags.md, serde_with/src/ser/duplicates.rs, serde_with/src/ser/impls.rs, serde_with/tests/indexmap_2.rs, serde_with_macros/Cargo.toml, serde_with_test/Cargo.toml
Introduces a new feature flag `indexmap_2` that enables the support.
Tests are copied from the v1 support.
Closes #621
=> Add trait implementations for indexmap v2

serde_with/src/content/de.rs, serde_with/src/de/impls.rs, serde_with/src/utils.rs
Upstream serde has a new implementation of the cautious size hint
function, which takes into consideration the size of the elements.
Use the same implementation in serde_with.
https://github.com/serde-rs/serde/pull/2495
bors r+
=> Sync the size_hint changes from serde

serde_with/src/utils/duration.rs
=> Properly handle i64::MIN when converting to Duration

Cargo.toml, serde_with/Cargo.toml, serde_with/tests/version_numbers.rs, serde_with_macros/Cargo.toml, serde_with_test/Cargo.toml
Move shared metadata, like license, repository, or edition to the
workspace, such that all crates use the single definition.
=> Move shared metadata to workspace definition

.github/workflows/ci.yaml, Cargo.lock, serde_with/Cargo.toml, serde_with/src/de/duplicates.rs, serde_with/src/de/impls.rs, serde_with/src/duplicate_key_impls/error_on_duplicate.rs, serde_with/src/duplicate_key_impls/first_value_wins.rs, serde_with/src/duplicate_key_impls/last_value_wins.rs, serde_with/src/guide/feature_flags.md, serde_with/src/ser/duplicates.rs, serde_with/src/ser/impls.rs, serde_with/tests/hashbrown.rs, serde_with/tests/hashbrown_0_14.rs
This PR is not yet ready to merge as I've never setup a `#[no_std]` friendly crate before. Looking for guidance for how to properly setup the Cargo.toml to support this (and perhaps validate this holds true).
=> feat: add optional support for hasbrown Map & Set

serde_with_macros/src/lib.rs
=> Mention serde_as in docstring for 'apply'

Cargo.lock, serde_with/Cargo.toml, serde_with_macros/Cargo.toml
As far as I can tell, the minimum version of 1.0.157 is unnecessary. The way I've determined that is just from running the build + tests:
```
cargo build --workspace
cargo test --workspace
```
This addresses https://github.com/jonasbb/serde_with/issues/651. For my needs at least 1.0.152 is actually sufficient (rather than 1.0.149), though we could try go lower.
=> Decrease minimum serde version to 1.0.152

serde_with/src/de/impls.rs, serde_with/src/lib.rs, serde_with/src/ser/impls.rs, serde_with/tests/serde_as/lib.rs
I have encountered a case where I would like to use `Bound<Cow<'a, str>>` and borrow the string from the deserialized buffer instead of copying. To use `BorrowStr`, I had to add support for `core::ops::Bound` to `serde_with`.
=> Add support for core::ops::Bound

Cargo.toml
https://github.com/rust-lang/rust-clippy/issues/12075
=> Disable clippy::doc_markdown lint, due to FP

serde_with/src/lib.rs, serde_with/src/schemars_0_8.rs
This is written on top of #676.
---
Implementing `JsonSchema` directly on `serde_with::Schema<T, TA>` works fine when within `serde_with`. Once you are outside the crate, however, the orphan rules prevent you from adding impls of the form
```rust
impl JsonSchema for Schema<T, MyCustomType> { ... }
```
We would like users to be able to make that impl (or something equivalent) so we need to find a way to make it work. We make this work by adding a new layer of trait indirection.
This PR introduces a new `JsonSchemaAs<T>` trait, adds a blanket
```rust
impl<T, TA> JsonSchema for Schema<T, TA> where TA: JsonSchemaAs<T>
```
and then changes all the existing impls to be for `JsonSchemaAs<T>` instead of on `Schema<T, TA>`.
Now, when a user wants to add json schema support for their own type they …
=> Allow external crates to add their own `JsonSchema` impls for custom `SerializeAs` and `DeserializeAs` types

Cargo.lock, Cargo.toml, README.md, serde_with/CHANGELOG.md, serde_with/Cargo.toml, serde_with/src/lib.rs, serde_with/tests/schemars_0_8.rs, serde_with_macros/CHANGELOG.md, serde_with_macros/src/lib.rs, serde_with_macros/src/utils.rs
The `#[schemars]` annotation emitted by `#[serde_as]` will cause errors if the user has already added an existing `#[schemars(with = ...)]` annotation. This ends up being rather annoying since there's no way to work around the error other than to manually expand what `#[serde_as]` does.
I ended up running into this when I was trying to convert some of my existing code to use the new integration instead of manually sticking `#[schemars(with = "blah")]` everywhere.
This PR fixes the issue by making `#[serde_as]` avoid emitting the schemars attribute if there is an existing one of the field that specifies any one of
- `#[schemars(with = "...")]`
- `#[schemars(serialize_with = "...")]`
- `#[schemars(deserialize_with = "...")]`
The actual code is a bit more involved (e.g. `serialize_as` …
=> Avoid emitting a `#[schemars(with = "...")]` annotation when one already exists

serde_with/src/schemars_0_8.rs, serde_with/tests/schemars_0_8.rs
This PR continues where #679 left off. Since the impls get more complicated as we go on I will be chunking them up into smaller PRs so that reviewing them stays manageable. I also don't plan on doing more than 1 or maybe 2 PRs concurrently. I just considered #682 important enough that it should jump the queue. 
- `JsonSchemaFor` impls for both `BytesOrString` and `BoolFromInt`
- Tests for both of the above
- `BytesOrString`'s schema is represented as an enum that can be either a string or an array of bytes. The one difference is that the string representation is marked as "writeOnly" as it is never emitted.
- I originally also did something similar for `BoolFromInt<Flexible>` but I didn't think that this was useful compared to the extra confusion when reading the schema. I have changed it …
=> Add `JsonSchema` impls for `BytesOrString` and `BoolFromInt`

serde_with/src/schemars_0_8.rs, serde_with/tests/schemars_0_8.rs, serde_with/tests/schemars_0_8/snapshots/duration.json
This PR picks up from where #683 left off.
---
Since there are quite a few different Duration and Timestamp adaptors most of this PR is just macro-driven copy paste. In earlier iterations it was much worse but with the help of an internal trait I was able to reduce it down to something manageable.
This PR includes:
- `JsonSchemaAs` impls for all `DurationXXX` and `TimestampYYY` adaptors for all formats and supported library types.
- Tests for the above
- Modelling `Strict` versions is easy. Their schema is just that of the underlying format.
- `Flexible` adaptors required some judgement calls:
- I have decided not to distinguish between integers and numbers - everything is typed as `"instanceType": "number"`. I think this is more likely to be useful in practice than trying to make a …
=> Add JsonSchemaAs impls for all Duration and Timestamp adaptors

serde_with/CHANGELOG.md, serde_with/src/de/impls.rs, serde_with/src/guide/serde_as_transformations.md, serde_with/src/lib.rs, serde_with/src/ser/impls.rs, serde_with/tests/serde_as/lib.rs
Closes #687 
Used to specify different transformations for text-based and binary formats.
=> Add IfIsHumanReadable

Cargo.lock
CI is impacted by https://github.com/tkaitchuck/aHash/issues/200, which is fixed in ahash 0.8.7. I see the following in the jobs that ran on https://github.com/jonasbb/serde_with/pull/694:
```console
error[E0635]: unknown feature `stdsimd`
--> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.8.6/src/lib.rs:99:42
|
99 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
|                                          ^^^^^^^
```
=> Update ahash to 0.8.7 to accommodate stdsimd change in nightly

Cargo.lock, serde_with/Cargo.toml, serde_with/src/flatten_maybe.rs, serde_with/src/lib.rs
This allows serde, and other crates downstream of it like serde_json, to compile in parallel with serde_derive. Without this PR, in any dependency graph that pulls in serde_with, first serde_derive would need to compile, then serde would need to compile, then serde_json would need to compile.
https://github.com/sharkdp/bat/pull/2815 has a diagram of the impact of this change.
=> Eliminate dependency on serde's "derive" feature

serde_with/src/schemars_0_8.rs, serde_with/tests/schemars_0_8.rs, serde_with/tests/schemars_0_8/snapshots/enum_map.json
It's been a little busy but I'm back with yet another PR :)
This is the first one that really involves a custom deserialize implementation. `EnumMap` involves transforming a list of enums to a map and to generate its schema we end up needing to do the same to the schema.
Basically, we end up transforming
```json
{
"type": "object",
"oneOf": [
{ "properties": { "A": "..." } },
{ "properties": { "B": "..." } }
]
}       
```
into
```json
{
"type": "object",
"properties": {
"A": "...",
"B": "..."
}
}
```
I have also included a number of tests that I think should cover most of the different cases.
- If the schema for the inner type doesn't match what would be expected for a rust enum then we'll end up generating an invalid overall schema. I don't think this is an issue since it doesn't appear …
=> Implement `JsonSchemaAs` for `EnumMap`

serde_with/src/de/impls.rs, serde_with/src/enum_map.rs, serde_with/src/key_value_map.rs, serde_with/src/utils/duration.rs, serde_with/tests/derives/serialize_display.rs, serde_with/tests/serde_as/enum_map.rs
write! with a single string argument is not properly optimized and using
write_str generates better code:
https://github.com/serde-rs/serde/pull/2697
https://github.com/rust-lang/rust/pull/121001
=> Replace uses of write! with write_str and write_fmt

serde_with/src/de/duplicates.rs, serde_with/src/de/impls.rs, serde_with/src/schemars_0_8.rs, serde_with/src/ser/duplicates.rs, serde_with/src/ser/impls.rs, serde_with/tests/chrono_0_4.rs, serde_with/tests/hashbrown_0_14.rs, serde_with/tests/indexmap_1.rs, serde_with/tests/indexmap_2.rs, serde_with/tests/schemars_0_8.rs, serde_with/tests/serde_as/frominto.rs, serde_with/tests/serde_as/fromintoref.rs, serde_with/tests/serde_as/pickfirst.rs, serde_with/tests/with_prefix.rs, serde_with_macros/src/utils.rs
* FIx redundant import warnings that appeared on nightly
=> Fix warnings

.github/workflows/publish-crates-io.yaml, .github/workflows/scorecards-analysis.yml, CONTRIBUTING.md, README.md, serde_with/CHANGELOG.md, serde_with/Cargo.toml, serde_with/src/chrono_0_4.rs, serde_with/src/de/mod.rs, serde_with/src/guide.md, serde_with/src/guide/serde_as.md, serde_with/src/guide/serde_as_transformations.md, serde_with/src/lib.rs, serde_with/src/schemars_0_8.rs, serde_with/src/ser/mod.rs, serde_with/src/time_0_3.rs, serde_with/tests/chrono_0_4.rs, serde_with/tests/serde_as/map_tuple_list.rs, serde_with_macros/CHANGELOG.md, serde_with_macros/src/lib.rs, serde_with_macros/tests/compile-fail/serde_as.rs
This PR just fixes a bunch of small typos and grammatical issues – no functional changes. Thank you for the work on this library!
=> Fix various small typos & grammar

Cargo.toml, serde_with/src/de/impls.rs, serde_with/src/rust.rs, serde_with/src/schemars_0_8.rs, serde_with/src/utils.rs, serde_with_macros/src/lib.rs
Disable `unused_qualifications` and enable `doc_markdown`.
=> Fix lint issues on nightly

serde_with/CHANGELOG.md, serde_with/tests/schemars_0_8.rs, serde_with_macros/CHANGELOG.md, serde_with_macros/src/lib.rs
I spotted #712 and since I had finally gotten around to making another set of PRs I figured I might as well submit a fix.
This treats a `#[schemars(schema_with = "...")]` attribute the same as a `#[schemars(with = "...")]` attribute when deciding whether to emit our own.
There is also a new test case that validates that everything works as expected.
Fixes #712
=> Avoid emitting `with` when there's already a `schema_with` annotation

serde_with/src/lib.rs
It looks like I missed this during my first PR. Since the other modules already have this it is confusing that it is missing.
=> Add `#[doc(cfg(..))]` annotation to the schemars_0_8 module

serde_with/src/schemars_0_8.rs, serde_with/tests/schemars_0_8.rs
It looks like `IfIsHumanReadable` was added after I wrote all the existing impls so here's a bonus PR!
This one is straightforward. `serde_json` always has `is_human_readable` set to true so we use the schema for the human readable variant. I have also included a test to that effect.
=> Add `JsonSchemaAs` impl for `IfIsHumanReadable`

serde_with/src/schemars_0_8.rs, serde_with/tests/schemars_0_8.rs, serde_with/tests/schemars_0_8/snapshots/key_value_map.json, serde_with/tests/schemars_0_8/snapshots/key_value_map_enum.json, serde_with/tests/schemars_0_8/snapshots/key_value_map_flatten.json
I'm back with yet another PR! This time we're doing `KeyValueMap`.
I think this one is probably the most complicated conversion that needs to be done to make the schema work. We need to convert a schema that looks like this
```json
{
"type": "object",
"properties": {
"$key$": "...",
"a": "...",
},
"required": ["$key$", "a"]
}
```
into this
```json
{
"type": "object",
"additionalProperties": {
"type": "object",
"required": ["a"],
"properties": { "a": "..." }
}
}
```
On its own that is not to bad but it gets more complicated since we also have to deal subschemas which can be generated from types that make use of `#[serde(untagged)]` and `#[serde(flatten)]`. See the doc comment on `kvmap_transform_schema` for more details.
- I'm not entirely sure this is correct in the presence of an …
=> Implement JsonSchemaAs for KeyValueMap

serde_with/src/schemars_0_8.rs, serde_with/tests/schemars_0_8.rs, serde_with/tests/schemars_0_8/snapshots/one_or_many_prefer_one.json
Here's the next type. This one implements `JsonSchemaAs` for `OneOrMany`. It is fortunately much simpler than `KeyValueMap`.
For `OneOrMany` the transformation we want to do is basically to take this schema
```json
{ "$ref": "..." }
```
and transform it into
```json
{
"anyOf": [
{ "$ref": "..." },
{
"type": "array",
"items": { "$ref": "..." }
}
]
}
```
that is, we change it so it can take either an array or a single value. The only difference between the `PreferOne` and the `PreferMany` variants is that the inner object is marked as `writeOnly: true`.
I have also included some tests that should cover pretty much everything.
=> Implement `JsonSchemaAs` for `OneOrMany`

Cargo.lock, Cargo.toml, README.md, serde_with/CHANGELOG.md, serde_with/Cargo.toml, serde_with/src/lib.rs, serde_with_macros/CHANGELOG.md, serde_with_macros/src/lib.rs
This includes many new `JsonSchemaAs` implementations and a fix to the
`serde_as` macro for `schemars` attributes.
=> Bump version to 3.7.0

serde_with/src/schemars_0_8.rs, serde_with/tests/schemars_0_8.rs, serde_with/tests/schemars_0_8/snapshots/pickfirst.json
This is the second-to-last type that I've got an implementation queued up for. The only one left after this is `Seq`.
This one is pretty straightforward: we put the involved schemas in an `anyOf` subschema. All the schemas except the first are annotated with `writeOnly: true` to indicate that they are only accepted when deserializing and not emitted when serializing. The one extra detail is that I've used an internal `allOf` in each element so that setting `writeOnly: true` works even if the schema of the type is a reference to an external schema.
I have also included tests and a snapshot test to show that everything works.
=> Implement `JsonSchemaAs` for `PickFirst`

serde_with/src/serde_conv.rs, serde_with_test/tests/serde_conv.rs
=> Add test that serde_conv will not trigger `clippy::ptr_arg`

serde_with/CHANGELOG.md, serde_with/src/de/impls.rs, serde_with/src/lib.rs, serde_with/src/ser/impls.rs, serde_with/tests/serde_as/lib.rs
Implements `SerializeAs` and `DeserializeAs` for `Pin<Box<T>>`, `Pin<Rc<T>>`, and `Pin<Arc<T>>`
=> Implement (De)Serialization for Pinned Smart Pointers

serde_with/CHANGELOG.md, serde_with/tests/schemars_0_8.rs, serde_with/tests/schemars_0_8/schemars_deserialize_only_bug_735.json, serde_with_macros/src/lib.rs
This is not supported by the schemars macro.
Closes #735
=> Do not emit schemars(deserialize_with = "...")

Cargo.lock
This removes bitflags v1 and winapi from the lock file.
windows* crates are updated to v0.52
=> Update parking_lot_cor, winapi-util, chrono, iana-time-zone, windows-core

serde_with/tests/chrono_0_4.rs, serde_with/tests/serde_as/time.rs
In serde 1.0.196, the "invalid type" error message for floats started
adding a trailing ".0" if no decimal point was already part of the
formatted float, causing tests to fail like:
---- test_chrono_timestamp_seconds_with_frac stdout ----
error: expect test failed
--> serde_with/tests/chrono_0_4.rs:551:9
Expect:
----
invalid type: floating point `0`, expected a string at line 1 column 3
----
Actual:
----
invalid type: floating point `0.0`, expected a string at line 1 column 3
----
Change the tests to use a test value of 0.1, so the test will work both
pre- and post-serde 1.0.196.
=> Fix tests with serde >= 1.0.196

serde_with/src/schemars_0_8.rs, serde_with/tests/schemars_0_8.rs, serde_with/tests/schemars_0_8/snapshots/one_or_many_nested.json
Currently, there is an `impl JsonSchema for WrapSchema<OneOrMany<...>>`. This works fine if you only directly need `OneOrMany` but causes errors if you want to nest it (e.g. `Option<OneOrMany<_>>`).
This PR changes the impl to a `JsonSchemaAs` impl, which is the correct approach. I think I just missed these ones during a rebase. In any case, the change should be fully backwards compatible due to the blanket schema impl.
I have added a snapshot test. The actual snapshot doesn't matter - the real test is that the struct below compiles
```rust
#[serde_as]
#[derive(Serialize, Deserialize, JsonSchema)]
struct Test {
#[serde_as(as = "Option<OneOrMany<_>>")]
optional_vec: Option<Vec<String>>,
}
```
=> Implement JsonSchemaAs for OneOrMany instead of JsonSchema

.github/workflows/audit.yaml, .github/workflows/ci.yaml, serde_with/tests/base64.rs, serde_with/tests/chrono_0_4.rs, serde_with/tests/derives/lib.rs, serde_with/tests/hashbrown_0_14.rs, serde_with/tests/hex.rs, serde_with/tests/indexmap_1.rs, serde_with/tests/indexmap_2.rs, serde_with/tests/json.rs, serde_with/tests/rust.rs, serde_with/tests/schemars_0_8.rs, serde_with/tests/serde_as/lib.rs, serde_with/tests/time_0_3.rs, serde_with/tests/utils.rs, serde_with/tests/version_numbers.rs, serde_with/tests/with_prefix.rs, serde_with_macros/tests/apply.rs, serde_with_macros/tests/compiler-messages.rs, serde_with_macros/tests/serde_as_issue_267.rs, serde_with_macros/tests/skip_serializing_null.rs, serde_with_macros/tests/version_numbers.rs
Add Rust 1.80 to the list of tested versions
=> Cleanup CI config files

serde_with/tests/schemars_0_8.rs, serde_with_macros/src/lazy_bool.rs, serde_with_macros/src/lib.rs, serde_with_macros/src/utils.rs
With this commit, `cfg_attr` will be handled properly. The current implementation does not accept e.g.:
```rust
#[serde_as]
#[derive(JsonSchema, Serialize)]
struct Test {
#[serde_as(as = "DisplayFromStr")]
#[cfg_attr(any(), arbitrary("some" |weird| syntax::<bool, 2>()))]
#[cfg_attr(any(), schemars(rename = "foo"), schemars(range(min = 0)))]
custom: i32,
}
```
Because due to https://github.com/jonasbb/serde_with/blob/master/serde_with_macros/src/utils.rs#L91, the parser does not accept `cfg_attr` with multiple arguments, which is allowed, see e.g. https://doc.rust-lang.org/reference/conditional-compilation.html#the-cfg_attr-attribute. Another issue I’ve found with `arbitrary` where some unexpected errors due to this custom parser: …
=> feat(serde_with_macros): proper handling of `cfg_attr` and `schemars`

.github/workflows/ci.yaml, Cargo.lock, serde_with/CHANGELOG.md, serde_with/Cargo.toml, serde_with/src/de/duplicates.rs, serde_with/src/de/impls.rs, serde_with/src/de/skip_error.rs, serde_with/src/duplicate_key_impls/error_on_duplicate.rs, serde_with/src/duplicate_key_impls/first_value_wins.rs, serde_with/src/duplicate_key_impls/last_value_wins.rs, serde_with/src/schemars_0_8.rs, serde_with/src/ser/duplicates.rs, serde_with/src/ser/impls.rs, serde_with/src/ser/skip_error.rs, serde_with/tests/hashbrown_0_15.rs
Hashbrown support for v0.14 is already included and this just extends
the code to cover the new crate version.
Closes #787
=> Add support for hashbrown v0.15

.github/workflows/ci.yaml, Cargo.lock, Cargo.toml, serde_with/Cargo.toml, serde_with/src/schemars_0_8.rs, serde_with/tests/schemars_0_8.rs, serde_with/tests/schemars_0_8/schemars_deserialize_only_bug_735.json, serde_with/tests/schemars_0_8/snapshots/enum_map.json, serde_with/tests/schemars_0_8/snapshots/key_value_map.json, serde_with/tests/schemars_0_8/snapshots/key_value_map_enum.json, serde_with/tests/schemars_0_8/snapshots/key_value_map_flatten.json, serde_with/tests/schemars_0_8/snapshots/one_or_many_nested.json, serde_with/tests/schemars_0_8/snapshots/one_or_many_prefer_one.json, serde_with/tests/schemars_0_8/snapshots/pickfirst.json, serde_with/tests/schemars_0_8/snapshots/pickfirst_nested.json, serde_with/tests/utils.rs
=> Generated schemas are not valid when using rust style names in ref

.github/workflows/ci.yaml
There is a problem of testing proc-macro crates with Rust 1.83:
https://github.com/xd009642/tarpaulin/issues/1642#issuecomment-2517795748
=> Do not run tarpaulin on serde_with_macros

.cargo/audit.toml, bors.toml, serde_with/Cargo.toml, serde_with_macros/Cargo.toml, serde_with_test/Cargo.toml
Just a minor cleanup to keep spacing consistent
=> Reformat all cargo.toml

serde_with/src/chrono_0_4.rs, serde_with/src/content/de.rs, serde_with/src/de/impls.rs, serde_with/src/ser/impls.rs, serde_with/src/time_0_3.rs, serde_with/src/utils.rs, serde_with/src/utils/duration.rs, serde_with/tests/serde_as/enum_map.rs
This removes some potential arithmetic issues
See #771 for reference
=> Remove some `as` casts

serde_with/src/content/de.rs, serde_with/src/de/impls.rs, serde_with/src/utils.rs
Tests are omitted since they do not work with `serde_json`. They are treated as large floats.
=> Generate better error messages when encountering unexpected i128/u128 values during deserialization

serde_with/Cargo.toml
As seen here
https://github.com/rust-lang/docs.rs/issues/506#issuecomment-2670501688
=> Make docs.rs link to the stable documentation of the std crates

README.md, serde_with/src/lib.rs
The old badge always used the latest workflow run status, which can be
from failing PRs. The new badge shows the status of the `ci.yaml` on the
`master` branch.`
=> Update GitHub Actions CI badge

serde_with/CHANGELOG.md, serde_with/src/rust.rs, serde_with/tests/rust.rs
`rust::unwrap_or_skip` was incompatible with references (zero-copy). See examples of this incompatibility in the new tests.
=> makes unwrap_or_skip compatible with references (zero-copy)

serde_with_macros/CHANGELOG.md, serde_with_macros/src/lib.rs, serde_with_test/tests/derive_display_alt_fromstr.rs
This PR introduces the `SerializeDisplayAlt` derive macro.
This is an alternative to the `SerializeDisplay` macro except instead of using the plain formatting like `format!("{}", ...)`, it serializes with the `Formatter::alternate` flag set to true, like `format!("{:#}", ...)`.
=> Add `SerializeDisplayAlt` macro

serde_with/CHANGELOG.md, serde_with/src/de/impls.rs, serde_with/src/utils/duration.rs
This includes the other fractionless variants as well, such as
DurationMilliSeconds, DurationMicroSeconds, and DurationNanoSeconds.
=> Implement DeserializeAs for DurationSeconds without std feature

serde_with/src/schemars_0_8.rs, serde_with/tests/schemars_0_8.rs
This backports the commit c14ced8811a92993956039076badbfda8011bbf8 from #849.
=> Fix min_properties handing in schemars v0.8 code

.github/workflows/ci.yaml
Caching is not needed for rustfmt in CI, as it only operates on the
source code, thus no binary artifacts are produced.
=> Skip caching for rustfmt in CI

serde_with/src/content/de.rs, serde_with/src/schemars_0_8.rs, serde_with/src/schemars_0_9.rs, serde_with/src/schemars_1.rs, serde_with/src/utils.rs
* Remove unused derives from internal Content type
* Extract common DropGuard struct and NumberExt trait
* Remove unused derives and dead functions in schemars code
=> Dead code cleanup

serde_with/src/schemars_0_8.rs, serde_with/src/schemars_0_9.rs, serde_with/src/schemars_1.rs, serde_with/tests/schemars_0_8/main.rs, serde_with/tests/schemars_0_8/schemars_basic.json, serde_with/tests/schemars_0_9/main.rs, serde_with/tests/schemars_0_9/schemars_basic.json, serde_with/tests/schemars_1/main.rs, serde_with/tests/schemars_1/schemars_basic.json
This PR allows for the `serde_with::hex::Hex` type to be used with `schemars`
Updated the `schemars_basic` test cases with tests for lowercase and uppercase hex schemas
=> Allow for schema derivation for the Hex type

serde_with/CHANGELOG.md, serde_with/Cargo.toml, serde_with_macros/CHANGELOG.md, serde_with_macros/Cargo.toml
A recent rust nightly added the ability to show macro expansions in the
rustdoc output. Since this crate uses macros for many trait
implementations, this is useful for users trying to understand the macro
output.
https://github.com/rust-lang/rust/pull/137229
Closes #879
=> Generate macro expansion in rustdoc

.github/workflows/publish-crates-io.yaml
This uses GitHub OIDC tokens to authenticate to crates.io, removing the
need for a long-lived token stored in GitHub secrets.
https://crates.io/docs/trusted-publishing
Closes #880
=> Enable crates.io trusted publishing
